Repository idx-academy/spa-orders, pull requests merged in 2024-06, with the labels that each got.

#24 Init folder structure inside code folder
  code/src/assets/icons/.gitkeep
  code/src/assets/images/.gitkeep
  code/src/components/.gitkeep
  code/src/constants/.gitkeep
  code/src/hooks/.gitkeep
  code/src/layouts/.gitkeep
  code/src/scss/.gitkeep
  code/src/store/.gitkeep
  code/src/types/.gitkeep
  code/src/utils/.gitkeep
Labels: feature, front end, priority:high

#28 Fix eslint and prettier setup
  code/.prettierrc
  code/eslint.config.mjs
Labels: front end

#29 Setup scss structure
  code/config/webpack.config.js
  code/package-lock.json
  code/package.json
  code/src/main.tsx
  code/src/scss/.gitkeep
  code/src/styles/scss/base/_reset.scss
  code/src/styles/scss/base/_root.scss
  code/src/styles/scss/foundation/_all.scss
  code/src/styles/scss/foundation/_colors.scss
  code/src/styles/scss/foundation/_mixins.scss
  code/src/styles/scss/foundation/_typography.scss
  code/src/styles/scss/foundation/_variables.scss
  code/src/styles/scss/global.scss
Labels: feature, front end, sprint 1, priority:high

#31 Install mui framework
  code/config/setup-tests.js
  code/config/webpack.config.js
  code/package-lock.json
  code/package.json
  code/src/layouts/.gitkeep
  code/src/layouts/app-wrapper/PageWrapper.tsx
  code/src/layouts/app-wrapper/tests/pageWrapper.test.tsx
  code/src/main.tsx
  code/src/scss/.gitkeep
  code/src/shared/modules/application/application.tsx
  code/src/styles/muiTheme.ts
  code/src/styles/scss/base/_reset.scss
  code/src/styles/scss/base/_root.scss
  code/src/styles/scss/foundation/_all.scss
  code/src/styles/scss/foundation/_colors.scss
  code/src/styles/scss/foundation/_mixins.scss
  code/src/styles/scss/foundation/_typography.scss
  code/src/styles/scss/foundation/_variables.scss
  code/src/styles/scss/global.scss
  code/tsconfig.json
Labels: feature, frontend

#33 Integrated translation
  code/src/main.tsx
  code/src/messages.ts
  code/src/pages/dashboard/dashboard.tsx
  code/src/pages/dashboard/i18n/en.json
  code/src/pages/dashboard/i18n/index.ts
  code/src/pages/dashboard/i18n/uk.json
  code/src/shared/i18n/I18nProvider.tsx
  code/src/shared/modules/application/application.tsx
  code/src/shared/modules/application/i18n/es.json
  code/src/shared/modules/application/i18n/index.ts
  code/src/shared/modules/application/i18n/uk.json
  code/src/shared/modules/application/tests/application.test.tsx
  package-lock.json
Labels: feature, frontend

#36 Feature/16/setup colors and typography
  code/config/webpack.config.js
  code/src/components/.gitkeep
  code/src/components/app-button/AppButton.scss
  code/src/components/app-button/AppButton.tsx
  code/src/components/app-typography/AppTypography.scss
  code/src/components/app-typography/AppTypography.tsx
  code/src/styles/scss/base/_root.scss
  code/src/styles/scss/foundation/_colors.scss
  code/src/styles/scss/foundation/_functions.scss
  code/src/styles/scss/foundation/_mixins.scss
  code/src/styles/scss/foundation/_typography.scss
  code/src/styles/scss/foundation/_variables.scss
  code/src/styles/scss/global.scss
Labels: feature, frontend, sprint 1, priority:high

#38 Deleted accidently added package-lock
  package-lock.json
Labels: frontend

#34 Setup RTK + query
  code/src/constants/.gitkeep
  code/src/constants/methods.ts
  code/src/constants/requests.ts
  code/src/hooks/.gitkeep
  code/src/hooks/use-redux.ts
  code/src/main.tsx
  code/src/pages/dashboard/dashboard.tsx
  code/src/store/.gitkeep
  code/src/store/api/appApi.ts
  code/src/store/api/todosApi.ts
  code/src/store/constants.ts
  code/src/store/slices/todoSlice.ts
  code/src/store/store.ts
  code/src/utils/.gitkeep
  code/src/utils/createUrlPath.ts
Labels: feature, frontend, sprint 1

#44 Create a AppButton component
  code/src/components/app-button/AppButton.scss
  code/src/components/app-button/AppButton.test.tsx
  code/src/components/app-button/AppButton.tsx
  code/src/shared/modules/application/application.scss
  code/src/shared/modules/application/application.tsx
  code/src/styles/scss/foundation/_variables.scss
Labels: feature, frontend, sprint 1, ui

#43 Implement intro section
  code/src/assets/images/.gitkeep
  code/src/assets/images/home-page/hero_section_img.jpg
  code/src/components/app-typography/AppTypography.scss
  code/src/layouts/app-banner/AppBanner.scss
  code/src/layouts/app-banner/AppBanner.tsx
  code/src/shared/modules/application/application.tsx
  code/src/shared/modules/application/i18n/en.json
  code/src/shared/modules/application/i18n/uk.json
  code/src/shared/modules/application/tests/AappBanner.test.tsx
  code/src/shared/modules/application/tests/PageWrapper.test.tsx
  code/src/styles/scss/global.scss
Labels: feature, frontend, sprint 1, ui

#40 Add tests for AppTypography component
  code/src/components/app-typography/AppTypography.test.tsx
  code/src/components/app-typography/AppTypography.tsx
Labels: priority:low, frontend, sprint 1, tests

#46 Created footer
  code/src/components/app-typography/AppTypography.tsx
  code/src/layouts/app-footer/AppFooter.constants.tsx
  code/src/layouts/app-footer/AppFooter.scss
  code/src/layouts/app-footer/AppFooter.test.jsx
  code/src/layouts/app-footer/AppFooter.tsx
  code/src/pages/dashboard/i18n/en.json
  code/src/pages/dashboard/i18n/uk.json
  code/src/shared/i18n/I18nProvider.tsx
  code/src/shared/modules/application/application.tsx
  code/src/shared/modules/application/tests/application.test.tsx
Labels: feature, frontend, sprint 1, ui

#45 Created Header with Categories
  code/config/__mocks__/fileMock.js
  code/config/jest.config.js
  code/config/webpack.config.js
  code/package-lock.json
  code/package.json
  code/src/assets/images/logo.jpeg
  code/src/declaration.d.ts
  code/src/layouts/app-banner/AppBanner.scss
  code/src/layouts/app-banner/AppBanner.test.tsx
  code/src/layouts/app-banner/AppBanner.tsx
  code/src/layouts/app-header/AppHeader.test.tsx
  code/src/layouts/app-header/AppHeader.tsx
  code/src/layouts/app-header/components/categories/Categories.constants.ts
  code/src/layouts/app-header/components/categories/Categories.scss
  code/src/layouts/app-header/components/categories/Categories.test.tsx
  code/src/layouts/app-header/components/categories/Categories.tsx
  code/src/layouts/app-header/components/header/Header.scss
  code/src/layouts/app-header/components/header/Header.test.tsx
  code/src/layouts/app-header/components/header/Header.tsx
  code/src/layouts/app-wrapper/PageWrapper.test.tsx
  code/src/pages/dashboard/dashboard.tsx
  code/src/pages/dashboard/i18n/en.json
  code/src/pages/dashboard/i18n/uk.json
  code/src/pages/dashboard/index.tsx
  code/src/shared/modules/application/application.tsx
  code/src/shared/modules/application/i18n/uk.json
  code/src/shared/modules/application/tests/applicationTestExample.tsx
  code/src/styles/scss/foundation/_variables.scss
  code/stryker-config/stryker-incremental.json
Labels: feature, frontend, sprint 1, ui

#50 Refactor test setup, add mock for FormattedMessage component
  code/config/setup-tests.js
  code/src/components/app-typography/AppTypography.test.tsx
  code/src/layouts/app-banner/AppBanner.test.tsx
  code/src/layouts/app-footer/AppFooter.test.jsx
  code/src/layouts/app-header/AppHeader.test.tsx
  code/src/layouts/app-header/components/header/Header.test.tsx
Labels: bug, priority:medium, frontend, sprint 1, refactor, tests

#52 Added .env.local file and dotenv-webpack package to extract envs
  .gitignore
  code/config/webpack.config.js
  code/package-lock.json
  code/package.json
  code/src/components/app-typography/AppTypography.tsx
  code/src/store/api/appApi.ts
  code/src/store/api/todosApi.ts
Labels: feature, frontend

#56 Changed translations structure
  code/src/layouts/app-banner/messages/en.json
  code/src/layouts/app-banner/messages/index.ts
  code/src/layouts/app-banner/messages/uk.json
  code/src/layouts/app-footer/messages/en.json
  code/src/layouts/app-footer/messages/index.ts
  code/src/layouts/app-footer/messages/uk.json
  code/src/messages.ts
  code/src/pages/dashboard/i18n/index.ts
  code/src/shared/i18n/common-messages/en.json
  code/src/shared/i18n/common-messages/index.ts
  code/src/shared/i18n/common-messages/uk.json
  code/src/shared/modules/application/i18n/index.ts
Labels: frontend, refactor

#65 Created AppBox, AppContainer components
  code/src/components/app-box/AppBox.test.tsx
  code/src/components/app-box/AppBox.tsx
  code/src/components/app-container/AppContainer.test.tsx
  code/src/components/app-container/AppContainer.tsx
  code/src/layouts/app-banner/AppBanner.tsx
  code/src/layouts/app-footer/AppFooter.tsx
  code/src/layouts/app-header/components/categories/Categories.tsx
  code/src/layouts/app-header/components/header/Header.tsx
  code/src/layouts/app-wrapper/PageWrapper.tsx
  code/src/layouts/page-wrapper/PageWrapper.test.tsx
  code/src/layouts/page-wrapper/PageWrapper.tsx
  code/src/shared/modules/application/application.tsx
Labels: feature, frontend, sprint 1, refactor, ui, design system

#64 Added AppIconButton component
  code/src/components/app-icon-button/AppIconButton.test.tsx
  code/src/components/app-icon-button/AppIconButton.tsx
Labels: priority:low, feature, frontend, ui, design system

#67 Init AppLink component
  code/src/components/app-link/AppLink.scss
  code/src/components/app-link/AppLink.test.tsx
  code/src/components/app-link/AppLink.tsx
  code/src/components/app-link/AppLink.types.ts
  code/src/styles/foundation/_mixins.scss
  code/src/styles/foundation/_variables.scss
Labels: feature, frontend, ui, design system

#70 Created AppBadge component
  code/src/components/app-badge/AppBadge.scss
  code/src/components/app-badge/AppBadge.test.tsx
  code/src/components/app-badge/AppBadge.tsx
  code/src/components/app-badge/AppBadge.types.ts
  code/src/layouts/app-header/components/header/Header.tsx
  code/src/shared/modules/application/application.tsx
  code/src/utils/cn.ts
Labels: feature, frontend, ui, design system

#73 Refactor app banner
  code/src/assets/images/home-page/hero_section_img.jpg
  code/src/assets/images/home-page/intro-banner/hero-section-img-1.webp
  code/src/assets/images/home-page/intro-banner/hero-section-img-2.webp
  code/src/assets/images/home-page/intro-banner/hero-section-img-3.webp
  code/src/components/app-badge/AppBadge.scss
  code/src/components/app-badge/AppBadge.tsx
  code/src/components/app-badge/AppBadge.types.ts
  code/src/components/app-button/AppButton.scss
  code/src/hooks/use-interval-switcher/useIntervalSwitcher.test.ts
  code/src/hooks/use-interval-switcher/useIntervalSwitcher.ts
  code/src/hooks/use-redux/useRedux.ts
  code/src/layouts/app-banner/AppBanner.scss
  code/src/layouts/app-banner/AppBanner.test.tsx
  code/src/layouts/app-banner/AppBanner.tsx
  code/src/layouts/app-banner/messages/en.json
  code/src/layouts/app-banner/messages/index.ts
  code/src/layouts/app-banner/messages/uk.json
  code/src/layouts/app-header/components/header/Header.scss
  code/src/layouts/app-header/components/header/Header.tsx
  code/src/layouts/intro-banner/IntroBanner.constants.ts
  code/src/layouts/intro-banner/IntroBanner.scss
  code/src/layouts/intro-banner/IntroBanner.test.tsx
  code/src/layouts/intro-banner/IntroBanner.tsx
  code/src/layouts/intro-banner/messages/en.json
  code/src/layouts/intro-banner/messages/index.ts
  code/src/layouts/intro-banner/messages/uk.json
  code/src/messages.ts
  code/src/shared/modules/application/application.tsx
Labels: feature, frontend, refactor

#76 Replace classnames by cn
  code/src/components/app-button/AppButton.tsx
  code/src/components/app-link/AppLink.tsx
  code/src/components/app-typography/AppTypography.tsx
Labels: frontend, refactor

#90 Added route for 'shop all' page
  code/src/constants/routes.ts
  code/src/layouts/app-header/AppHeader.test.tsx
  code/src/layouts/app-header/components/categories/Categories.constants.ts
  code/src/layouts/app-header/components/categories/Categories.scss
  code/src/layouts/app-header/components/categories/Categories.test.tsx
  code/src/layouts/app-header/components/categories/Categories.tsx
  code/src/pages/products/ProductsPage.tsx
  code/src/routes/routes.tsx
Labels: feature, frontend

#54 Create mock product items on mock server and render them into UI
  code/src/components/product-card/ProductCard.scss
  code/src/components/product-card/ProductCard.tsx
  code/src/constants/requests.ts
  code/src/layouts/best-sellers/BestSellers.scss
  code/src/layouts/best-sellers/BestSellers.tsx
  code/src/layouts/best-sellers/messages/en.json
  code/src/layouts/best-sellers/messages/index.ts
  code/src/layouts/best-sellers/messages/uk.json
  code/src/layouts/page-wrapper/PageWrapper.tsx
  code/src/messages.ts
  code/src/pages/home/HomePage.tsx
  code/src/store/api/appApi.ts
  code/src/store/api/productsApi.ts
  code/src/store/api/todosApi.ts
  code/src/store/constants.ts
  code/src/store/slices/productsSlice.ts
  code/src/store/slices/todoSlice.ts
  code/src/store/store.ts
  code/src/styles/foundation/_variables.scss
  code/src/types/product.types.ts
  mock-backend/package-lock.json
  mock-backend/package.json
  mock-backend/src/app.js
  mock-backend/src/controllers/.gitkeep
  mock-backend/src/controllers/productController.js
  mock-backend/src/data/mokedData.js
  mock-backend/src/routes/.gitkeep
  mock-backend/src/routes/productRoutes.js
Labels: feature, frontend

#69 Refactor app header
  code/src/assets/images/logo.jpeg
  code/src/assets/images/logo.png
  code/src/components/app-box/AppBox.tsx
  code/src/components/app-logo/AppLogo.test.tsx
  code/src/components/app-logo/AppLogo.tsx
  code/src/components/product-card/ProductCard.scss
  code/src/constants/routes.ts
  code/src/layouts/app-header/AppHeader.test.tsx
  code/src/layouts/app-header/AppHeader.tsx
  code/src/layouts/app-header/components/categories/Categories.constants.ts
  code/src/layouts/app-header/components/categories/Categories.scss
  code/src/layouts/app-header/components/categories/Categories.test.tsx
  code/src/layouts/app-header/components/categories/Categories.tsx
  code/src/layouts/app-header/components/header/Header.scss
  code/src/layouts/app-header/components/header/Header.test.tsx
  code/src/layouts/app-header/components/header/Header.tsx
  code/src/layouts/header/Header.scss
  code/src/layouts/header/Header.test.tsx
  code/src/layouts/header/Header.tsx
  code/src/layouts/header/components/header-categories/HeaderCategories.constants.ts
  code/src/layouts/header/components/header-categories/HeaderCategories.scss
  code/src/layouts/header/components/header-categories/HeaderCategories.test.tsx
  code/src/layouts/header/components/header-categories/HeaderCategories.tsx
  code/src/layouts/header/components/header-toolbar/HeaderToolbar.scss
  code/src/layouts/header/components/header-toolbar/HeaderToolbar.test.tsx
  code/src/layouts/header/components/header-toolbar/HeaderToolbar.tsx
  code/src/layouts/header/hooks/use-sticky-header/useStickyHeader.ts
  code/src/layouts/root-layout/RootLayout.tsx
  code/src/styles/foundation/_mixins.scss
  code/src/styles/foundation/_variables.scss
Labels: feature, priority:medium, frontend, refactor, ui

#55 Category section
  code/src/assets/images/home-page/category-section/computer-image.jpg
  code/src/assets/images/home-page/category-section/mobile-image.jpg
  code/src/assets/images/home-page/category-section/tablet-image.jpg
  code/src/layouts/category-section/CategorySection.constants.ts
  code/src/layouts/category-section/CategorySection.scss
  code/src/layouts/category-section/CategorySection.test.tsx
  code/src/layouts/category-section/CategorySection.tsx
  code/src/layouts/category-section/components/CategoryItem.tsx
  code/src/layouts/category-section/messages/en.json
  code/src/layouts/category-section/messages/index.ts
  code/src/layouts/category-section/messages/uk.json
  code/src/messages.ts
  code/src/pages/home/HomePage.tsx
Labels: feature, frontend, sprint 1, ui

#97 Fixed containers width
  code/src/layouts/best-sellers/BestSellers.scss
  code/src/layouts/category-section/CategorySection.scss
  code/src/layouts/category-section/CategorySection.tsx
  code/src/layouts/page-wrapper/PageWrapper.scss
  code/src/layouts/page-wrapper/PageWrapper.tsx
  code/src/layouts/subintro/Subintro.tsx
  code/src/layouts/subintro/subintro.scss
  code/src/styles/global.scss
Labels: bug, frontend, priority:high

#93 Created AppLoader component
  code/src/components/app-button/AppButton.scss
  code/src/components/app-button/AppButton.tsx
  code/src/components/app-loader/AppLoader.scss
  code/src/components/app-loader/AppLoader.test.tsx
  code/src/components/app-loader/AppLoader.tsx
  code/src/components/app-loader/AppLoader.types.ts
Labels: feature, frontend, ui, design system, sprint 2

#98 Configured webpack for bg images
  code/config/webpack.config.js
  code/package-lock.json
  code/package.json
  code/src/layouts/intro-banner/IntroBanner.scss
  code/src/layouts/intro-banner/IntroBanner.tsx
Labels: bug, priority:low, frontend, refactor, sprint 2

#109 Create cta section and fix small issues
  code/src/assets/images/home-page/call-to-action-section/computer.webp
  code/src/assets/images/home-page/call-to-action-section/phone.webp
  code/src/components/app-button/AppButton.scss
  code/src/components/app-typography/AppTypography.scss
  code/src/layouts/call-to-action/CallToAction.constants.ts
  code/src/layouts/call-to-action/CallToAction.scss
  code/src/layouts/call-to-action/CallToAction.test.tsx
  code/src/layouts/call-to-action/CallToAction.tsx
  code/src/layouts/call-to-action/components/call-to-action-item/CallToActionItem.test.tsx
  code/src/layouts/call-to-action/components/call-to-action-item/CallToActionItem.tsx
  code/src/layouts/call-to-action/messages/en.json
  code/src/layouts/call-to-action/messages/index.ts
  code/src/layouts/call-to-action/messages/uk.json
  code/src/layouts/footer/AppFooter.test.tsx
  code/src/layouts/subintro/Subintro.scss
  code/src/layouts/subintro/Subintro.tsx
  code/src/messages.ts
  code/src/pages/home/HomePage.tsx
Labels: feature, frontend, ui, sprint 2

#113 Created view for all products
  code/src/components/app-button/AppButton.scss
  code/src/components/app-button/AppButton.tsx
  code/src/components/product-card/ProductCard.scss
  code/src/components/product-card/ProductCard.tsx
  code/src/components/product-card/messages/en.json
  code/src/components/product-card/messages/index.ts
  code/src/components/product-card/messages/uk.json
  code/src/messages.ts
  code/src/pages/products/ProductsPage.scss
  code/src/pages/products/ProductsPage.test.tsx
  code/src/pages/products/ProductsPage.tsx
  code/src/pages/products/messages/en.json
  code/src/pages/products/messages/index.ts
  code/src/pages/products/messages/uk.json
Labels: feature, frontend, sprint 2

#116 Pushed footer to the bottom of the page
  code/src/layouts/root-layout/RootLayout.scss
  code/src/layouts/root-layout/RootLayout.tsx
  code/src/styles/foundation/_variables.scss
Labels: frontend, sprint 2

#118 Created empty modal view
  code/src/context/ModalContext.tsx
  code/src/layouts/header/components/header-toolbar/HeaderToolbar.tsx
  code/src/layouts/modals/auth/AuthModal.scss
  code/src/layouts/modals/auth/AuthModal.test.tsx
  code/src/layouts/modals/auth/AuthModal.tsx
  code/src/layouts/modals/auth/messages/en.json
  code/src/layouts/modals/auth/messages/index.ts
  code/src/layouts/modals/auth/messages/uk.json
  code/src/main.tsx
  code/src/messages.ts
  code/src/utils/test-utils.tsx
Labels: feature, frontend, ui, sprint 2, auth

#127 Created app-accordion items
  code/src/components/app-accordion/AppAccordion.tsx
  code/src/components/app-accordion/app-accordion-details/AppAccordionDetails.test.tsx
  code/src/components/app-accordion/app-accordion-details/AppAccordionDetails.tsx
  code/src/components/app-accordion/app-accordion-details/AppAccordionDetails.types.ts
  code/src/components/app-accordion/app-accordion-summary/AppAccordionSummary.test.tsx
  code/src/components/app-accordion/app-accordion-summary/AppAccordionSummary.tsx
  code/src/components/app-accordion/app-accordion-summary/AppAccordionSummary.types.ts
  code/src/components/app-accordion/app-accorion-container/AppAccordionContainer.scss
  code/src/components/app-accordion/app-accorion-container/AppAccordionContainer.test.tsx
  code/src/components/app-accordion/app-accorion-container/AppAccordionContainer.tsx
  code/src/components/app-accordion/app-accorion-container/AppAccordionContainer.types.ts
  code/src/styles/foundation/_variables.scss
Labels: feature, ui, design system, sprint 2

#119 Moved types of app components to separate files
  code/src/components/app-box/AppBox.tsx
  code/src/components/app-box/AppBox.types.ts
  code/src/components/app-button/AppButton.tsx
  code/src/components/app-button/AppButton.types.ts
  code/src/components/app-container/AppContainer.tsx
  code/src/components/app-container/AppContainer.types.ts
  code/src/components/app-icon-button/AppIconButton.tsx
  code/src/components/app-icon-button/AppIconButton.types.ts
  code/src/components/app-logo/AppLogo.tsx
  code/src/components/app-logo/AppLogo.types.ts
  code/src/components/app-typography/AppTypography.test.tsx
  code/src/components/app-typography/AppTypography.tsx
  code/src/components/app-typography/AppTypography.types.ts
  code/src/layouts/page-wrapper/PageWrapper.tsx
Labels: priority:low, refactor, sprint 2

#125 Create AppSnackbar component and useSnackbar hook
  .gitignore
  code/reports/stryker/stryker.html
  code/reports/stryker/stryker.json
  code/src/components/app-snackbar/AppSnackbar.scss
  code/src/components/app-snackbar/AppSnackbar.test.tsx
  code/src/components/app-snackbar/AppSnackbar.tsx
  code/src/hooks/use-redux/useRedux.ts
  code/src/hooks/use-snackbar/useSnackbar.test.tsx
  code/src/hooks/use-snackbar/useSnackbar.ts
  code/src/main.tsx
  code/src/store/constants.ts
  code/src/store/slices/productsSlice.ts
  code/src/store/slices/snackbarSlice.ts
  code/src/store/store.ts
  code/src/styles/foundation/_variables.scss
  code/src/types/common.ts
  code/src/types/snackbar.types.ts
  code/src/utils/test-utils.tsx
  code/stryker-config/stryker-incremental.json
  code/stryker.log
Labels: feature, frontend, ui, sprint 2, auth

#120 Init auth and user slices
  code/src/App.tsx
  code/src/constants/common-messages/en.json
  code/src/constants/common-messages/uk.json
  code/src/constants/common.ts
  code/src/constants/requests.ts
  code/src/layouts/header/components/header-toolbar/HeaderToolbar.test.tsx
  code/src/layouts/header/components/header-toolbar/HeaderToolbar.tsx
  code/src/main.tsx
  code/src/store/api/appApi.ts
  code/src/store/api/authApi.ts
  code/src/store/constants.ts
  code/src/store/slices/userSlice.ts
  code/src/store/store.ts
  code/src/types/auth.types.ts
Labels: feature, frontend, sprint 2, auth

#126 Create AppInput component and AppInputWitIcon component
  code/src/components/app-input-with-icon/AppInputWithIcon.scss
  code/src/components/app-input-with-icon/AppInputWithIcon.test.tsx
  code/src/components/app-input-with-icon/AppInputWithIcon.tsx
  code/src/components/app-input-with-icon/AppInputWithIcon.types.ts
  code/src/components/app-input/AppInput.test.tsx
  code/src/components/app-input/AppInput.tsx
  code/src/components/app-input/AppInput.types.ts
  code/src/layouts/header/components/header-toolbar/HeaderToolbar.scss
  code/src/layouts/header/components/header-toolbar/HeaderToolbar.test.tsx
  code/src/layouts/header/components/header-toolbar/HeaderToolbar.tsx
Labels: frontend, auth

#135 Added lazy-loading to pages
  code/config/webpack.config.js
  code/src/components/app-skeleton/AppSkeleton.test.tsx
  code/src/components/app-skeleton/AppSkeleton.tsx
  code/src/components/app-skeleton/AppSkeleton.types.ts
  code/src/layouts/page-loading-fallback/PageLoadingFallback.scss
  code/src/layouts/page-loading-fallback/PageLoadingFallback.test.tsx
  code/src/layouts/page-loading-fallback/PageLoadingFallback.tsx
  code/src/layouts/page-loading-fallback/PageLoadingFallback.types.ts
  code/src/layouts/root-layout/RootLayout.tsx
  code/src/main.tsx
  code/src/routes/routes.tsx
  code/src/styles/foundation/_functions.scss
  code/tsconfig.json
Labels: feature, frontend

#131 Feature/122/order view page
  code/src/components/app-link/AppLink.tsx
  code/src/components/app-typography/AppTypography.scss
  code/src/components/app-typography/AppTypography.tsx
  code/src/components/app-typography/AppTypography.types.ts
  code/src/components/product-card/ProductCard.test.tsx
  code/src/components/product-card/ProductCard.tsx
  code/src/constants/orderStatuses.ts
  code/src/constants/routes.ts
  code/src/layouts/header/components/header-toolbar/HeaderToolbar.tsx
  code/src/layouts/order-item/OrderItem.constants.ts
  code/src/layouts/order-item/OrderItem.scss
  code/src/layouts/order-item/OrderItem.test.tsx
  code/src/layouts/order-item/OrderItem.tsx
  code/src/layouts/order-item/components/order-item-details/OrderItemDetails.scss
  code/src/layouts/order-item/components/order-item-details/OrderItemDetails.tsx
  code/src/layouts/order-item/components/order-product-item/OrderProductItem.scss
  code/src/layouts/order-item/components/order-product-item/OrderProductItem.tsx
  code/src/layouts/order-item/messages/en.json
  code/src/layouts/order-item/messages/index.ts
  code/src/layouts/order-item/messages/uk.json
  code/src/layouts/orders-list/OrdersList.scss
  code/src/layouts/orders-list/OrdersList.tsx
  code/src/messages.ts
  code/src/pages/orders/OrdersPage.scss
  code/src/pages/orders/OrdersPage.tsx
  code/src/routes/routes.tsx
  code/src/types/common.ts
  code/src/types/delivery.types.ts
  code/src/types/order.types.ts
  code/src/types/product.types.ts
  mock-backend/src/data/mokedData.js
Labels: feature, frontend, ui, sprint 2

#124 Added pagination
  code/src/components/app-pagination/AppPagination.test.tsx
  code/src/components/app-pagination/AppPagination.tsx
  code/src/components/app-pagination/AppPagination.types.ts
  code/src/layouts/best-sellers/BestSellers.constants.ts
  code/src/layouts/best-sellers/BestSellers.test.tsx
  code/src/layouts/best-sellers/BestSellers.tsx
  code/src/layouts/root-layout/RootLayout.tsx
  code/src/pages/products/ProductsPage.scss
  code/src/pages/products/ProductsPage.test.tsx
  code/src/pages/products/ProductsPage.tsx
  code/src/store/api/productsApi.ts
  mock-backend/src/controllers/productController.js
  mock-backend/src/data/mokedData.js
Labels: feature, frontend, sprint 2
