Repository idx-academy/spa-orders, pull requests merged in 2024-08, with the labels that each got.

#431 Created debounce and optimistic logic for changing product quantity
  code/src/hooks/use-debounced-value/useDebouncedValue.test.ts
  code/src/hooks/use-debounced-value/useDebouncedValue.ts
  code/src/hooks/use-user-cart-items/useUserCartItems.test.ts
  code/src/hooks/use-user-cart-items/useUserCartItems.ts
  code/src/pages/cart/CartPage.tsx
  code/src/pages/cart/components/cart-item/CartItem.test.tsx
  code/src/pages/cart/components/cart-item/CartItem.tsx
Labels: feature, frontend, spint 5

#379 Added AppLink component to category elements to make them clickable
  code/src/containers/category-section/CategorySection.constants.ts
  code/src/containers/category-section/CategorySection.scss
  code/src/containers/category-section/CategorySection.test.tsx
  code/src/containers/category-section/CategorySection.tsx
  code/src/containers/category-section/components/CategoryItem.tsx
  code/src/pages/products/ProductsPage.test.tsx
  code/src/pages/products/ProductsPage.tsx
  code/src/pages/products/messages/en.json
  code/src/pages/products/messages/uk.json
Labels: frontend, ui, sprint 4

#430 Add pagination for dashboard orders
  code/src/containers/dashboard-orders-filter-drawer/DashboardOrdersFilterDrawer.test.tsx
  code/src/containers/dashboard-orders-filter-drawer/DashboardOrdersFilterDrawer.tsx
  code/src/containers/dashboard-orders-filter-drawer/hooks/use-filtered-admin-orders/useFilteredAdminOrders.test.ts
  code/src/containers/dashboard-orders-filter-drawer/hooks/use-filtered-admin-orders/useFilteredAdminOrders.ts
  code/src/hooks/use-filters-with-apply/useFiltersWithApply.test.ts
  code/src/hooks/use-filters-with-apply/useFiltersWithApply.ts
  code/src/hooks/use-filters-with-apply/useFiltersWithApply.types.ts
  code/src/pages/dashboard/dashboard-orders/DashboardOrdersPage.scss
  code/src/pages/dashboard/dashboard-orders/DashboardOrdersPage.test.tsx
  code/src/pages/dashboard/dashboard-orders/DashboardOrdersPage.tsx
  code/src/types/order.types.ts
  mock-backend/src/controllers/orderConroller.js
  mock-backend/src/data/mokedOrders.js
Labels: feature, dashboard

#433 Add global scrollbar styles
  code/src/styles/global.scss
Labels: feature, frontend, ui, spint 5

#440 Edit admin layout
  code/src/constants/requests.ts
  code/src/layouts/dashboard-layout/components/dashboard-admin-tab-layout/DashboardAdminLayout.constants.tsx
  code/src/store/api/ordersApi.ts
Labels: frontend, dashboard

#437 Add is paid status changing to dashboard/orders page
  code/src/components/app-checkbox/AppCheckbox.types.ts
  code/src/constants/orderStatuses.ts
  code/src/containers/tables/orders-table/OrdersTable.constants.ts
  code/src/containers/tables/orders-table/OrdersTable.test.tsx
  code/src/containers/tables/orders-table/OrdersTable.tsx
  code/src/containers/tables/orders-table/components/orders-table-body/OrdersTableBody.scss
  code/src/containers/tables/orders-table/components/orders-table-body/OrdersTableBody.test.tsx
  code/src/containers/tables/orders-table/components/orders-table-body/OrdersTableBody.tsx
  code/src/containers/tables/orders-table/components/orders-table-head/OrdersTableHead.constants.ts
  code/src/containers/tables/orders-table/components/orders-table-head/OrdersTableHead.scss
  code/src/containers/tables/orders-table/messages/en.json
  code/src/containers/tables/orders-table/messages/uk.json
  code/src/messages.ts
  code/src/pages/dashboard-order-details/DashboardOrderDetails.constants.ts
  code/src/pages/dashboard-order-details/DashboardOrderDetailsPage.test.tsx
  code/src/store/api/ordersApi.ts
  code/src/styles/foundation/_variables.scss
  code/src/types/order.types.ts
  mock-backend/src/data/mokedOrders.js
Labels: feature, frontend

#435 Changes to skeleton footer container
  code/src/components/product-skeleton/ProductSkeleton.scss
Labels: bug, frontend, ui

#432 Added pagination for manager products
  code/src/components/app-pagination/AppPagination.tsx
  code/src/constants/requests.ts
  code/src/pages/dashboard/dashboard-products/DashboardProductsPage.scss
  code/src/pages/dashboard/dashboard-products/DashboardProductsPage.test.tsx
  code/src/pages/dashboard/dashboard-products/DashboardProductsPage.tsx
  code/src/store/api/productsApi.ts
  code/src/types/product.types.ts
  mock-backend/src/controllers/productController.js
  mock-backend/src/data/managerProducts.js
Labels: feature, frontend, spint 5

#449 Increased coverage of DashboardOrdersPage
  code/src/pages/dashboard/dashboard-orders/DashboardOrdersPage.test.tsx
Labels: frontend, refactor, tests, dashboard, spint 5

#447 Global search functionality
  code/src/assets/images/search/no-results.png
  code/src/components/app-input-base/AppInputBase.test.tsx
  code/src/components/app-input-base/AppInputBase.tsx
  code/src/components/app-input-base/AppInputBase.types.ts
  code/src/components/app-input-with-icon/AppInputWithIcon.test.tsx
  code/src/components/app-input-with-icon/AppInputWithIcon.tsx
  code/src/components/app-input-with-icon/AppInputWithIcon.types.ts
  code/src/constants/requests.ts
  code/src/hooks/use-on-click-outside/useOnClickOutside.test.tsx
  code/src/hooks/use-on-click-outside/useOnClickOutside.ts
  code/src/layouts/header/components/header-search-input-dropdown/HeaderSearchInputDropdown.scss
  code/src/layouts/header/components/header-search-input-dropdown/HeaderSearchInputDropdown.test.tsx
  code/src/layouts/header/components/header-search-input-dropdown/HeaderSearchInputDropdown.tsx
  code/src/layouts/header/components/header-search-input/HeaderSearchInput.scss
  code/src/layouts/header/components/header-search-input/HeaderSearchInput.test.tsx
  code/src/layouts/header/components/header-search-input/HeaderSearchInput.tsx
  code/src/layouts/header/components/header-toolbar/HeaderToolbar.test.tsx
  code/src/layouts/header/hooks/use-sticky-header/useStickyHeader.test.ts
  code/src/layouts/header/hooks/use-sticky-header/useStickyHeader.ts
  code/src/layouts/header/messages/en.json
  code/src/layouts/header/messages/index.ts
  code/src/layouts/header/messages/uk.json
  code/src/messages.ts
  code/src/store/api/productsApi.ts
  code/src/styles/foundation/_variables.scss
  code/src/types/product.types.ts
  mock-backend/src/controllers/productController.js
  mock-backend/src/routes/productRoutes.js
  mock-backend/src/utils/filterUtils.js
Labels: feature, frontend

#438 Implemented product filtering by category using backend endpoint
  code/src/containers/best-sellers/BestSellers.test.tsx
  code/src/containers/best-sellers/BestSellers.tsx
  code/src/pages/products/ProductsPage.test.tsx
  code/src/pages/products/ProductsPage.tsx
  code/src/types/product.types.ts
  code/src/utils/filter-products-by-category/categoryFilter.test.ts
  code/src/utils/filter-products-by-category/categoryFilter.ts
  mock-backend/src/controllers/productController.js
  mock-backend/src/utils/categoryFilter.js
Labels: feature, refactor, spint 5

#443 Added update product form
  code/src/constants/common-messages/en.json
  code/src/constants/common-messages/uk.json
  code/src/constants/requests.ts
  code/src/containers/forms/new-product-form/NewProductForm.test.tsx
  code/src/containers/forms/new-product-form/NewProductForm.tsx
  code/src/containers/forms/product-form/ProductForm.constants.ts
  code/src/containers/forms/product-form/ProductForm.scss
  code/src/containers/forms/product-form/ProductForm.types.ts
  code/src/containers/forms/product-form/UpdateProductForm.test.tsx
  code/src/containers/forms/product-form/UpdateProductForm.tsx
  code/src/containers/forms/product-form/components/additional-info/AdditionalInfo.test.tsx
  code/src/containers/forms/product-form/components/additional-info/AdditionalInfo.tsx
  code/src/containers/forms/product-form/components/image/Image.test.tsx
  code/src/containers/forms/product-form/components/image/Image.tsx
  code/src/containers/forms/product-form/components/main-info/MainInfo.test.tsx
  code/src/containers/forms/product-form/components/main-info/MainInfo.tsx
  code/src/containers/forms/product-form/hooks/use-update-product/useUpdateProduct.test.ts
  code/src/containers/forms/product-form/hooks/use-update-product/useUpdateProduct.ts
  code/src/containers/forms/product-form/messages/en.json
  code/src/containers/forms/product-form/messages/index.ts
  code/src/containers/forms/product-form/messages/uk.json
  code/src/containers/forms/product-form/utils/filter-dirty-fields/filterDirtyFields.test.ts
  code/src/containers/forms/product-form/utils/filter-dirty-fields/filterDirtyFields.ts
  code/src/containers/forms/product-form/utils/get-default-values/getDefaultValues.test.ts
  code/src/containers/forms/product-form/utils/get-default-values/getDefaultValues.ts
  code/src/containers/forms/product-form/utils/get-request-body-from-values/getRequestBodyFromValues.test.ts
  code/src/containers/forms/product-form/utils/get-request-body-from-values/getRequestBodyFromValues.ts
  code/src/containers/tables/products-table/ProductsTable.test.tsx
  code/src/containers/tables/products-table/components/products-table-body/ProductsTableBody.tsx
  code/src/messages.ts
  code/src/pages/dashboard/dashboard-update-product/DashboardUpdateProductPage.tsx
  code/src/pages/dashboard/dashboard-update-product/components/dashboard-update-product-container/DashboardUpdateProductContainer.test.tsx
  code/src/pages/dashboard/dashboard-update-product/components/dashboard-update-product-container/DashboardUpdateProductContainer.tsx
  code/src/store/api/productsApi.ts
  code/src/types/product.types.ts
  code/src/utils/get-tag-in/getTagIn.test.tsx
  code/src/utils/get-tag-in/getTagIn.ts
  code/src/utils/validators/productScheme.ts
  mock-backend/src/data/managerProducts.js
Labels: feature, frontend, spint 5

#420 Change logic of AppRangeSlider to sync state with value correctly
  code/src/components/app-range-slider/AppRangeSlider.test.tsx
  code/src/components/app-range-slider/AppRangeSlider.tsx
  code/src/components/app-range-slider/AppRangeSlider.types.ts
  code/src/components/app-range-slider/utils/check-within-range/checkWithinRange.test.ts
  code/src/components/app-range-slider/utils/check-within-range/checkWithinRange.ts
  code/src/components/app-range-slider/utils/parse-range-values/parseRangeValues.test.ts
  code/src/components/app-range-slider/utils/parse-range-values/parseRangeValues.ts
  code/src/containers/dashboard-orders-filter-drawer/DashboardOrdersFilterDrawer.scss
  code/src/containers/dashboard-orders-filter-drawer/DashboardOrdersFilterDrawer.test.tsx
  code/src/containers/dashboard-orders-filter-drawer/DashboardOrdersFilterDrawer.tsx
  code/src/containers/dashboard-orders-filter-drawer/hooks/use-filtered-admin-orders/useFilteredAdminOrders.constants.ts
  code/src/pages/dashboard/dashboard-orders/DashboardOrdersPage.tsx
Labels: bug, frontend, spint 5

#455 Refactored create product
  code/src/containers/forms/new-product-form/NewProductForm.constants.ts
  code/src/containers/forms/new-product-form/NewProductForm.scss
  code/src/containers/forms/new-product-form/NewProductForm.test.tsx
  code/src/containers/forms/new-product-form/NewProductForm.tsx
  code/src/containers/forms/new-product-form/NewProductForm.types.ts
  code/src/containers/forms/new-product-form/components/image-preview/ImagePreview.test.tsx
  code/src/containers/forms/new-product-form/components/image-preview/ImagePreview.tsx
  code/src/containers/forms/new-product-form/messages/en.json
  code/src/containers/forms/new-product-form/messages/index.ts
  code/src/containers/forms/new-product-form/messages/uk.json
  code/src/containers/forms/product-form/ProductForm.constants.ts
  code/src/containers/forms/product-form/ProductForm.types.ts
  code/src/containers/forms/product-form/components/create-product-form/CreateProductForm.test.tsx
  code/src/containers/forms/product-form/components/create-product-form/CreateProductForm.tsx
  code/src/containers/forms/product-form/components/main-info/MainInfo.test.tsx
  code/src/containers/forms/product-form/components/update-product-form/UpdateProductForm.test.tsx
  code/src/containers/forms/product-form/components/update-product-form/UpdateProductForm.tsx
  code/src/containers/forms/product-form/hooks/use-create-product/useCreateProduct.test.ts
  code/src/containers/forms/product-form/hooks/use-create-product/useCreateProduct.ts
  code/src/containers/forms/product-form/messages/en.json
  code/src/containers/forms/product-form/messages/uk.json
  code/src/messages.ts
  code/src/pages/dashboard/dashboard-new-product/DashboardNewProductPage.test.tsx
  code/src/pages/dashboard/dashboard-new-product/DashboardNewProductPage.tsx
  code/src/pages/dashboard/dashboard-update-product/components/dashboard-update-product-container/DashboardUpdateProductContainer.test.tsx
  code/src/pages/dashboard/dashboard-update-product/components/dashboard-update-product-container/DashboardUpdateProductContainer.tsx
  code/src/types/product.types.ts
  code/src/utils/validators/productCreationScheme.ts
  code/src/utils/validators/productScheme.ts
Labels: frontend, refactor, spint 5

#454 Reintroduced pagination to the products page
  code/src/containers/products-container/ProductsContainer.scss
  code/src/pages/products/ProductsPage.test.tsx
  code/src/pages/products/ProductsPage.tsx
  mock-backend/src/controllers/productController.js
Labels: feature, frontend

#459 Change manager order status and isPaid status for manager and admin
  code/src/containers/order-item/OrderItem.test.tsx
  code/src/containers/order-item/components/order-item-details/OrderProductDetails.test.tsx
  code/src/containers/orders-list/OrdersList.test.tsx
  code/src/containers/tables/orders-table/OrdersTable.constants.ts
  code/src/containers/tables/orders-table/components/orders-table-body/OrdersTableBody.test.tsx
  code/src/containers/tables/orders-table/components/orders-table-body/OrdersTableBody.tsx
  code/src/types/order.types.ts
  mock-backend/src/data/mokedOrders.js
Labels: feature, dashboard

#458 Created additional cart page tests steps and fix token warning with e2e
  code/src/components/product-card/ProductCard.tsx
  code/src/layouts/header/components/header-categories/HeaderCategories.tsx
  code/src/pages/cart/CartPage.tsx
  e2e/cypress/test_module/cypress/features/cart-page/cart-page.feature
  e2e/cypress/test_module/cypress/support/commands.ts
  e2e/cypress/test_module/cypress/support/helpers.ts
  e2e/cypress/test_module/cypress/support/step_definitions/cart-page.steps.ts
Labels: bug, frontend, tests, spint 5

#450 Add logic for buy now button on product details page
  code/src/components/product-card/ProductCard.test.tsx
  code/src/components/product-card/ProductCard.tsx
  code/src/components/product-card/ProductCard.types.ts
  code/src/containers/products-container/ProductsContainer.test.tsx
  code/src/containers/products-container/ProductsContainer.tsx
  code/src/hooks/use-add-to-cart-or-open-drawer/useAddToCartOrOpenDrawer.test.tsx
  code/src/hooks/use-add-to-cart-or-open-drawer/useAddToCartOrOpenDrawer.tsx
  code/src/hooks/use-get-cart/useGetCart.test.ts
  code/src/hooks/use-get-cart/useGetCart.ts
  code/src/pages/product-details/components/buy-now-button/BuyNowButton.test.tsx
  code/src/pages/product-details/components/buy-now-button/BuyNowButton.tsx
  code/src/pages/product-details/components/product-details-container/ProductDetailsContainer.test.tsx
  code/src/pages/product-details/components/product-details-container/ProductDetailsContainer.tsx
  code/src/pages/product-details/messages/en.json
  code/src/pages/product-details/messages/uk.json
Labels: feature, priority:medium, frontend, ui, spint 5

#461 Add pagination to users dashboard tab
  code/src/components/app-pagination/AppPagination.test.tsx
  code/src/components/app-pagination/AppPagination.tsx
  code/src/constants/requests.ts
  code/src/containers/dashboard-orders-filter-drawer/hooks/use-filtered-admin-orders/useFilteredAdminOrders.ts
  code/src/containers/pagination-block/PaginationBlock.scss
  code/src/containers/pagination-block/PaginationBlock.test.tsx
  code/src/containers/pagination-block/PaginationBlock.tsx
  code/src/containers/tables/orders-table/components/orders-table-body/OrdersTableBody.tsx
  code/src/hooks/use-pagination/usePagination.test.ts
  code/src/hooks/use-pagination/usePagination.ts
  code/src/pages/dashboard/dashboard-orders/DashboardOrdersPage.scss
  code/src/pages/dashboard/dashboard-orders/DashboardOrdersPage.tsx
  code/src/pages/dashboard/dashboard-products/DashboardProductsPage.scss
  code/src/pages/dashboard/dashboard-products/DashboardProductsPage.tsx
  code/src/pages/dashboard/dashboard-users/DashboardUsersPage.tsx
  code/src/pages/products/ProductsPage.test.tsx
  code/src/pages/products/ProductsPage.tsx
  code/src/store/api/usersApi.ts
  code/src/types/user.types.ts
  mock-backend/src/controllers/orderConroller.js
  mock-backend/src/controllers/productController.js
  mock-backend/src/controllers/usersController.js
  mock-backend/src/data/mockedUsers.js
  mock-backend/src/utils/parsePageable.js
Labels: feature, priority:medium, frontend, ui, spint 5

#465 Remove recommended sort param
  code/src/pages/products/ProductsPage.constants.tsx
  code/src/pages/products/ProductsPage.test.tsx
  code/src/pages/products/ProductsPage.tsx
Labels: bug, good first issue, frontend, priority:high, spint 5

#469 Change cart item styles handle empty value logic request
  code/src/hooks/use-update-cart-item-quantity/useUpdateCartItemQuantity.ts
  code/src/pages/cart/components/cart-item/CartItem.scss
  code/src/pages/cart/components/cart-item/CartItem.tsx
  code/src/store/api/cartApi.ts
Labels: bug, frontend, spint 5

#462 Implement search pagination
  code/src/components/app-menu-item/AppMenuItem.tsx
  code/src/components/app-menu-item/AppMenuItem.types.ts
  code/src/hooks/use-dropdown/useDropdown.test.ts
  code/src/hooks/use-dropdown/useDropdown.ts
  code/src/hooks/use-infinite-products-search/useInfiniteProductsSearch.test.ts
  code/src/hooks/use-infinite-products-search/useInfiniteProductsSearch.ts
  code/src/hooks/use-infinite-scroll/useInfiniteScroll.test.ts
  code/src/hooks/use-infinite-scroll/useInfiniteScroll.ts
  code/src/layouts/header/Header.test.tsx
  code/src/layouts/header/components/header-search-input-dropdown/HeaderSearchInputDropdown.scss
  code/src/layouts/header/components/header-search-input-dropdown/HeaderSearchInputDropdown.test.tsx
  code/src/layouts/header/components/header-search-input-dropdown/HeaderSearchInputDropdown.tsx
  code/src/layouts/header/components/header-search-input/HeaderSearchInput.scss
  code/src/layouts/header/components/header-search-input/HeaderSearchInput.test.tsx
  code/src/layouts/header/components/header-search-input/HeaderSearchInput.tsx
  code/src/layouts/header/hooks/use-sticky-header/useStickyHeader.test.ts
  code/src/layouts/header/messages/uk.json
  code/src/store/api/productsApi.ts
  code/src/utils/render-with-providers/renderWithProviders.tsx
  code/src/utils/setup-mock-intersection-observer/setupMockIntersectionObserver.ts
  mock-backend/src/controllers/productController.js
Labels: feature, frontend, spint 5

#471 Add pagination for OrdersPage under ROLE_USER role
  code/src/constants/requests.ts
  code/src/containers/order-item/OrderItem.tsx
  code/src/pages/orders/OrdersPage.test.tsx
  code/src/pages/orders/OrdersPage.tsx
  code/src/types/order.types.ts
Labels: feature, priority:medium, frontend, ui, spint 5

#467 Add search field to search order by user email
  code/src/components/app-search-input/AppSearchInput.scss
  code/src/components/app-search-input/AppSearchInput.test.tsx
  code/src/components/app-search-input/AppSearchInput.tsx
  code/src/components/app-search-input/AppSearchInput.types.ts
  code/src/containers/dashboard-orders-filter-drawer/hooks/use-filtered-admin-orders/useFilteredAdminOrders.constants.ts
  code/src/containers/dashboard-orders-filter-drawer/hooks/use-filtered-admin-orders/useFilteredAdminOrders.test.ts
  code/src/containers/dashboard-orders-filter-drawer/hooks/use-filtered-admin-orders/useFilteredAdminOrders.ts
  code/src/containers/dashboard-orders-filter-drawer/hooks/use-filtered-admin-orders/useFilteredAdminOrders.types.ts
  code/src/pages/dashboard/dashboard-orders/DashboardOrdersPage.scss
  code/src/pages/dashboard/dashboard-orders/DashboardOrdersPage.test.tsx
  code/src/pages/dashboard/dashboard-orders/DashboardOrdersPage.tsx
  code/src/pages/dashboard/dashboard-orders/messages/en.json
  code/src/pages/dashboard/dashboard-orders/messages/uk.json
  code/src/types/order.types.ts
Labels: feature, dashboard

#460 Added product details page for manager
  code/src/components/product-description/ProductDescription.scss
  code/src/components/product-description/ProductDescription.tsx
  code/src/components/product-description/ProductDescription.types.ts
  code/src/constants/common-messages/en.json
  code/src/constants/common-messages/uk.json
  code/src/constants/routes.ts
  code/src/containers/forms/product-form/ProductForm.constants.ts
  code/src/containers/forms/product-form/components/additional-info/AdditionalInfo.tsx
  code/src/containers/forms/product-form/components/create-product-form/CreateProductForm.test.tsx
  code/src/containers/forms/product-form/components/image/Image.tsx
  code/src/containers/forms/product-form/components/main-info/MainInfo.tsx
  code/src/containers/forms/product-form/components/update-product-form/UpdateProductForm.test.tsx
  code/src/containers/forms/product-form/hooks/use-create-product/useCreateProduct.test.ts
  code/src/containers/forms/product-form/hooks/use-create-product/useCreateProduct.ts
  code/src/containers/forms/product-form/messages/en.json
  code/src/containers/forms/product-form/messages/uk.json
  code/src/containers/tables/products-table/components/products-table-body/ProductsTableBody.tsx
  code/src/messages.ts
  code/src/pages/dashboard/dashboard-product/DashboardProductPage.constants.ts
  code/src/pages/dashboard/dashboard-product/DashboardProductPage.test.tsx
  code/src/pages/dashboard/dashboard-product/DashboardProductPage.tsx
  code/src/pages/dashboard/dashboard-product/DashboardProductPage.types.ts
  code/src/pages/dashboard/dashboard-product/components/dashboard-product-container/DashboardProductContainer.scss
  code/src/pages/dashboard/dashboard-product/components/dashboard-product-container/DashboardProductContainer.test.tsx
  code/src/pages/dashboard/dashboard-product/components/dashboard-product-container/DashboardProductContainer.tsx
  code/src/pages/dashboard/dashboard-product/messages/en.json
  code/src/pages/dashboard/dashboard-product/messages/index.ts
  code/src/pages/dashboard/dashboard-product/messages/uk.json
  code/src/pages/dashboard/dashboard-update-product/components/dashboard-update-product-container/DashboardUpdateProductContainer.test.tsx
  code/src/pages/dashboard/dashboard-update-product/components/dashboard-update-product-container/DashboardUpdateProductContainer.tsx
  code/src/pages/dashboard/dashboard-update-product/messages/en.json
  code/src/pages/dashboard/dashboard-update-product/messages/uk.json
  code/src/pages/product-details/components/product-details-container/ProductDetailsContainer.scss
  code/src/pages/product-details/components/product-details-container/ProductDetailsContainer.tsx
  code/src/routes/protectedRoutes.tsx
  code/src/store/api/productsApi.ts
Labels: feature, frontend, spint 5

#474 Increase global unit test coverage
  code/config/jest.config.js
  code/src/hooks/use-debounced-value/useDebouncedValue.test.ts
  code/src/hooks/use-infinite-products-search/useInfiniteProductsSearch.test.ts
  code/src/hooks/use-infinite-products-search/useInfiniteProductsSearch.ts
  code/src/pages/cart/CartPage.test.tsx
  code/src/pages/cart/components/cart-item/CartItem.test.tsx
  code/src/pages/dashboard/dashboard-product/components/dashboard-product-container/DashboardProductContainer.test.tsx
  code/src/pages/dashboard/dashboard-update-product/components/dashboard-update-product-container/DashboardUpdateProductContainer.test.tsx
  code/src/utils/create-url-path/createUrlPath.test.tsx
  code/src/utils/setup-mock-intersection-observer/setupMockIntersectionObserver.test.ts
  code/src/utils/setup-mock-intersection-observer/setupMockIntersectionObserver.ts
Labels: tests, spint 5

#480 Added fallback to invalid image
  code/src/assets/images/default-product-image.png
  code/src/components/product-card/ProductCard.test.tsx
  code/src/components/product-card/ProductCard.tsx
Labels: bug, frontend, spint 5

#477 Fixed checkbox bug
  code/src/containers/forms/product-form/ProductForm.types.ts
  code/src/containers/forms/product-form/components/additional-info/AdditionalInfo.tsx
  code/src/containers/forms/product-form/components/update-product-form/UpdateProductForm.tsx
  code/src/store/api/productsApi.ts
Labels: bug, frontend, spint 5

#475 Added searching for manager products page
  code/src/components/product-card/ProductCard.test.tsx
  code/src/pages/dashboard/dashboard-orders/DashboardOrdersPage.tsx
  code/src/pages/dashboard/dashboard-products/DashboardProductsPage.scss
  code/src/pages/dashboard/dashboard-products/DashboardProductsPage.test.tsx
  code/src/pages/dashboard/dashboard-products/DashboardProductsPage.tsx
  code/src/pages/dashboard/dashboard-products/DashboardProductsPage.types.ts
  code/src/pages/dashboard/dashboard-products/components/dashboard-products-header/DashboardProductsHeader.test.tsx
  code/src/pages/dashboard/dashboard-products/components/dashboard-products-header/DashboardProductsHeader.tsx
  code/src/pages/dashboard/dashboard-products/messages/en.json
  code/src/pages/dashboard/dashboard-products/messages/uk.json
  code/src/types/product.types.ts
Labels: feature, frontend, spint 5

#466 Created functions that handle products per page dynamically
  code/src/constants/breakpoints.ts
  code/src/pages/products/ProductsPage.test.tsx
  code/src/pages/products/ProductsPage.tsx
  code/src/utils/check-screen-size/useScreenSize.test.ts
  code/src/utils/check-screen-size/useScreenSize.ts
  code/src/utils/set-product-size/setProductsPerPageSize.test.ts
  code/src/utils/set-product-size/setProductsPerPageSize.ts
Labels: feature, frontend, spint 5

#483 Changed quantity error message
  code/src/hooks/use-update-cart-item-quantity/useUpdateCartItemQuantity.ts
Labels: bug, frontend, spint 5

#482 Fix infinite loading search
  code/src/hooks/use-infinite-products-search/useInfiniteProductsSearch.ts
  code/src/layouts/header/components/header-search-input-dropdown/HeaderSearchInputDropdown.tsx
  code/src/layouts/header/components/header-search-input/HeaderSearchInput.test.tsx
  code/src/layouts/header/components/header-search-input/HeaderSearchInput.tsx
Labels: bug, frontend, spint 5

#479 Improve loading state in ProductDetailsPage
  code/src/pages/product-details/components/product-details-container/ProductDetailsContainer.test.tsx
  code/src/pages/product-details/components/product-details-container/ProductDetailsContainer.tsx
Labels: bug, priority:high, ui, spint 5

#487 Remove constants folder from mutation tests
  code/stryker.conf.js
Labels: frontend, tests, spint 5

#485 Added e2e tests for product form
  code/src/containers/forms/product-form/components/additional-info/AdditionalInfo.tsx
  code/src/containers/forms/product-form/components/create-product-form/CreateProductForm.tsx
  code/src/containers/forms/product-form/components/image/Image.tsx
  code/src/containers/forms/product-form/components/main-info/MainInfo.tsx
  code/src/containers/forms/product-form/components/update-product-form/UpdateProductForm.test.tsx
  code/src/containers/forms/product-form/components/update-product-form/UpdateProductForm.tsx
  code/src/containers/tables/products-table/components/products-table-body/ProductsTableBody.tsx
  code/src/hooks/use-logout/useLogout.test.ts
  code/src/hooks/use-remove-from-cart/useRemoveFromCart.test.ts
  code/src/hooks/use-synchronize-cart/useSynchronizeCart.test.ts
  code/src/hooks/use-synchronize-cart/useSynchronizeCart.ts
  code/src/pages/dashboard/dashboard-orders/DashboardOrdersPage.test.tsx
  code/src/pages/dashboard/dashboard-products/DashboardProductsPage.test.tsx
  e2e/cypress/test_module/cypress/features/dashboard-page/new-product/new-product.feature
  e2e/cypress/test_module/cypress/features/dashboard-page/update-product/update-product.feature
  e2e/cypress/test_module/cypress/support/commands.ts
  e2e/cypress/test_module/cypress/support/index.ts
  e2e/cypress/test_module/cypress/support/step_definitions/common.steps.ts
  e2e/cypress/test_module/cypress/support/step_definitions/new-product.steps.ts
  e2e/cypress/test_module/cypress/support/step_definitions/product-form.steps.ts
  mock-backend/src/controllers/productController.js
  mock-backend/src/data/managerProducts.js
  mock-backend/src/routes/productRoutes.js
Labels: frontend, tests, spint 5

#484 e2e tests - fixing and adding
  code/src/containers/category-section/components/CategoryItem.tsx
  code/src/layouts/header/components/header-search-input-dropdown/HeaderSearchInputDropdown.tsx
  e2e/cypress/test_module/cypress/features/home-page/home-page-general.feature
  e2e/cypress/test_module/cypress/features/products-page/products-page.feature
  e2e/cypress/test_module/cypress/support/commands.ts
  e2e/cypress/test_module/cypress/support/index.ts
  e2e/cypress/test_module/cypress/support/step_definitions/home-page-general.steps.ts
  e2e/cypress/test_module/cypress/support/step_definitions/logout.steps.ts
  e2e/cypress/test_module/cypress/support/step_definitions/products-page.steps.ts
Labels: tests

#489 Fix visual bugs
  code/src/components/product-card/ProductCard.scss
  code/src/components/product-card/ProductCard.tsx
  code/src/layouts/footer/components/footer-banner/FooterBanner.test.tsx
  code/src/layouts/footer/components/footer-banner/FooterBanner.tsx
  code/src/pages/cart/components/cart-item/CartItem.scss
  code/src/pages/cart/components/cart-item/CartItem.tsx
  code/src/pages/dashboard/dashboard-orders/DashboardOrdersPage.test.tsx
  code/src/pages/dashboard/dashboard-orders/DashboardOrdersPage.tsx
  code/src/pages/dashboard/dashboard-products/DashboardProductsPage.test.tsx
  code/src/pages/dashboard/dashboard-products/DashboardProductsPage.tsx
  code/src/pages/dashboard/dashboard-users/DashboardUsersPage.test.tsx
  code/src/pages/dashboard/dashboard-users/DashboardUsersPage.tsx
Labels: bug, feature, frontend
