Repository idx-academy/spa-orders, pull requests merged in 2024-07, with the labels that each got.

#138 Added useSignIn and useSignUp hooks and setup global error middleware for rtk
  code/src/constants/common-messages/uk.json
  code/src/constants/common.ts
  code/src/hooks/use-sign-in/useSignIn.test.ts
  code/src/hooks/use-sign-in/useSignIn.ts
  code/src/hooks/use-sign-up/useSignUp.test.ts
  code/src/hooks/use-sign-up/useSignUp.ts
  code/src/store/api/appApi.ts
  code/src/store/errorMiddleware.ts
  code/src/store/slices/snackbarSlice.ts
  code/src/store/slices/userSlice.ts
  code/src/store/store.ts
  code/src/types/common.ts
  mock-backend/package-lock.json
  mock-backend/package.json
  mock-backend/src/app.js
  mock-backend/src/controllers/authController.js
  mock-backend/src/error/APIError.js
  mock-backend/src/middlewares/error.js
  mock-backend/src/routes/authRoutes.js
  mock-backend/src/services/.gitkeep
  mock-backend/src/services/authService.js
  mock-backend/src/utils/wait.js
Labels: feature, frontend, sprint 2, auth

#130 Created dropdown with sorting logic
  code/src/components/app-dropdown/AppDropdown.scss
  code/src/components/app-dropdown/AppDropdown.test.tsx
  code/src/components/app-dropdown/AppDropdown.tsx
  code/src/components/app-dropdown/AppDropdown.types.ts
  code/src/components/app-dropdown/components/AppDropdownOptions.test.tsx
  code/src/components/app-dropdown/components/AppDropdownOptions.tsx
  code/src/components/app-dropdown/messages/en.json
  code/src/components/app-dropdown/messages/index.ts
  code/src/components/app-dropdown/messages/uk.json
  code/src/components/product-card/ProductCard.tsx
  code/src/components/product-card/messages/en.json
  code/src/components/product-card/messages/uk.json
  code/src/layouts/best-sellers/BestSellers.tsx
  code/src/messages.ts
  code/src/pages/products/ProductsPage.constants.tsx
  code/src/pages/products/ProductsPage.scss
  code/src/pages/products/ProductsPage.test.tsx
  code/src/pages/products/ProductsPage.tsx
  code/src/pages/products/messages/en.json
  code/src/pages/products/messages/uk.json
  code/src/store/api/productsApi.ts
  mock-backend/src/controllers/productController.js
  mock-backend/src/utils/sortUtils.js
Labels: feature, frontend, sprint 2

#143 Added tests for useStickyHeader hook
  code/src/layouts/header/hooks/use-sticky-header/useStickyHeader.test.ts
Labels: frontend, tests

#142 Created a formatPrice util
  code/src/components/product-card/ProductCard.test.tsx
  code/src/components/product-card/ProductCard.tsx
  code/src/layouts/order-item/OrderItem.test.tsx
  code/src/layouts/order-item/OrderItem.tsx
  code/src/layouts/order-item/components/order-product-item/OrderProductItem.tsx
  code/src/utils/formatPrice.ts
  code/src/utils/tests/formatPrice.test.ts
Labels: feature, frontend, sprint 2

#146 Created global User type
  code/src/hooks/use-sign-in/useSignIn.test.ts
  code/src/hooks/use-sign-up/useSignUp.test.ts
  code/src/store/slices/userSlice.ts
  code/src/types/auth.types.ts
  code/src/types/common.ts
  code/src/types/delivery.types.ts
  code/src/types/order.types.ts
  code/src/types/user.types.ts
Labels: feature, good first issue, priority:medium, frontend, sprint 2

#147 Increased tests coverage for files in components folder
  code/src/components/app-badge/AppBadge.test.tsx
  code/src/components/app-button/AppButton.test.tsx
  code/src/components/app-link/AppLink.test.tsx
  code/src/components/app-typography/AppTypography.test.tsx
Labels: frontend, tests, sprint 2

#148 Use input visibility hook, LoginForm and SignupForm
  code/src/components/app-input/AppInput.scss
  code/src/components/app-input/AppInput.test.tsx
  code/src/components/app-input/AppInput.tsx
  code/src/components/app-input/AppInput.types.ts
  code/src/hooks/use-input-visibility/useInputVisibility.test.ts
  code/src/hooks/use-input-visibility/useInputVisibility.tsx
  code/src/layouts/modals/auth/AuthModal.scss
  code/src/layouts/modals/auth/AuthModal.test.tsx
  code/src/layouts/modals/auth/AuthModal.tsx
  code/src/layouts/modals/auth/components/login-form/LoginForm.scss
  code/src/layouts/modals/auth/components/login-form/LoginForm.test.tsx
  code/src/layouts/modals/auth/components/login-form/LoginForm.tsx
  code/src/layouts/modals/auth/components/login-form/messages/en.json
  code/src/layouts/modals/auth/components/login-form/messages/index.ts
  code/src/layouts/modals/auth/components/login-form/messages/uk.json
  code/src/layouts/modals/auth/components/signup-form/SignupForm.scss
  code/src/layouts/modals/auth/components/signup-form/SignupForm.test.tsx
  code/src/layouts/modals/auth/components/signup-form/SignupForm.tsx
  code/src/layouts/modals/auth/components/signup-form/messages/en.json
  code/src/layouts/modals/auth/components/signup-form/messages/index.ts
  code/src/layouts/modals/auth/components/signup-form/messages/uk.json
  code/src/layouts/modals/auth/messages/en.json
  code/src/layouts/modals/auth/messages/uk.json
  code/src/messages.ts
Labels: feature, frontend, tests

#156 Created formatDate util
  code/src/layouts/order-item/OrderItem.test.tsx
  code/src/layouts/order-item/OrderItem.tsx
  code/src/utils/format-date/formatDate.test.ts
  code/src/utils/format-date/formatDate.ts
Labels: feature, frontend, refactor, ui

#144 Created orders endpoints
  code/src/constants/requests.ts
  code/src/layouts/header/components/header-toolbar/HeaderToolbar.scss
  code/src/layouts/header/components/header-toolbar/HeaderToolbar.test.tsx
  code/src/layouts/header/components/header-toolbar/HeaderToolbar.tsx
  code/src/layouts/order-item/components/order-product-item/OrderProductItem.scss
  code/src/layouts/order-item/components/order-product-item/OrderProductItem.tsx
  code/src/layouts/orders-list/OrdersList.scss
  code/src/layouts/orders-list/OrdersList.tsx
  code/src/messages.ts
  code/src/pages/orders/OrdersPage.scss
  code/src/pages/orders/OrdersPage.tsx
  code/src/pages/orders/messages/en.json
  code/src/pages/orders/messages/index.ts
  code/src/pages/orders/messages/uk.json
  code/src/store/api/ordersApi.ts
  code/src/styles/foundation/_mixins.scss
  code/src/types/order.types.ts
  mock-backend/src/app.js
  mock-backend/src/controllers/orderConroller.js
  mock-backend/src/data/mokedOrders.js
  mock-backend/src/routes/orderRoutes.js
Labels: feature, frontend, ui, sprint 2

#149 Added jwt token parsing and attaching to auth headers logic
  code/package-lock.json
  code/package.json
  code/src/constants/common.ts
  code/src/hooks/use-sign-in/useSignIn.test.ts
  code/src/hooks/use-sign-up/useSignUp.test.ts
  code/src/store/api/appApi.ts
  code/src/store/errorMiddleware.ts
  code/src/store/slices/userSlice.ts
  code/src/store/store.ts
  code/src/types/user.types.ts
  code/src/utils/check-jwt-expiration/checkJWTExpiration.test.ts
  code/src/utils/check-jwt-expiration/checkJWTExpiration.ts
Labels: feature, priority:medium, frontend, sprint 2, auth

#151 Add tests for root layout
  code/src/layouts/root-layout/RootLayout.test.tsx
Labels: priority:low, feature, frontend, tests, sprint 2

#159 Add translations to errors and refactored AppSnackbar to accept it
  code/src/components/app-snackbar/AppSnackbar.scss
  code/src/components/app-snackbar/AppSnackbar.test.tsx
  code/src/components/app-snackbar/AppSnackbar.tsx
  code/src/constants/common-messages/en.json
  code/src/constants/common-messages/uk.json
  code/src/constants/common.ts
  code/src/hooks/use-sign-in/useSignIn.test.ts
  code/src/hooks/use-sign-in/useSignIn.ts
  code/src/hooks/use-sign-up/useSignUp.test.ts
  code/src/hooks/use-sign-up/useSignUp.ts
  code/src/hooks/use-snackbar/useSnackbar.test.tsx
  code/src/layouts/header/Header.test.tsx
  code/src/layouts/header/components/header-toolbar/HeaderToolbar.test.tsx
  code/src/layouts/header/components/header-toolbar/HeaderToolbar.tsx
  code/src/store/errorMiddleware.ts
  code/src/types/snackbar.types.ts
Labels: priority:low, feature, good first issue, frontend, refactor

#167 Add ProtectedLayout for authorized users
  code/src/layouts/header/Header.test.tsx
  code/src/layouts/header/components/header-toolbar/HeaderToolbar.test.tsx
  code/src/layouts/header/components/header-toolbar/HeaderToolbar.tsx
  code/src/layouts/protected-layout/ProtectedLayout.test.tsx
  code/src/layouts/protected-layout/ProtectedLayout.tsx
  code/src/routes/guestRoutes.tsx
  code/src/routes/protectedRoutes.tsx
  code/src/routes/routes.tsx
  code/src/store/reducer.ts
  code/src/store/slices/userSlice.ts
  code/src/store/store.ts
  code/src/utils/test-utils.tsx
Labels: feature, frontend, refactor

#160 Created NotFound page and change view with layout
  code/src/messages.ts
  code/src/pages/not-found/NotFoundPage.scss
  code/src/pages/not-found/NotFoundPage.test.tsx
  code/src/pages/not-found/NotFoundPage.tsx
  code/src/pages/not-found/messages/en.json
  code/src/pages/not-found/messages/index.ts
  code/src/pages/not-found/messages/uk.json
  code/src/routes/routes.tsx
Labels: feature, frontend

#169 Refactored AppButton so it can be used as link
  code/src/components/app-button/AppButton.tsx
  code/src/components/app-button/AppButton.types.ts
  code/src/components/app-link/AppLink.types.ts
  code/src/layouts/call-to-action/components/call-to-action-item/CallToActionItem.tsx
  code/src/pages/not-found/NotFoundPage.tsx
Labels: frontend, refactor

#177 Hotfix changes for sorting with Java backend
  code/src/layouts/best-sellers/BestSellers.test.tsx
  code/src/layouts/best-sellers/BestSellers.tsx
  code/src/pages/products/ProductsPage.constants.tsx
  code/src/pages/products/ProductsPage.test.tsx
  code/src/pages/products/ProductsPage.tsx
  code/src/store/api/productsApi.ts
  mock-backend/src/utils/sortUtils.js
Labels: feature, frontend, priority:high, refactor

#179 Fix cta button style
  code/src/layouts/call-to-action/CallToAction.scss
Labels: bug, feature, priority:high, ui

#172 Refactor utils folder structure
  README.md
  code/src/components/app-accordion/app-accorion-container/AppAccordionContainer.tsx
  code/src/components/app-badge/AppBadge.tsx
  code/src/components/app-button/AppButton.tsx
  code/src/components/app-dropdown/AppDropdown.test.tsx
  code/src/components/app-dropdown/AppDropdown.tsx
  code/src/components/app-dropdown/components/AppDropdownOptions.test.tsx
  code/src/components/app-input-with-icon/AppInputWithIcon.tsx
  code/src/components/app-link/AppLink.test.tsx
  code/src/components/app-link/AppLink.tsx
  code/src/components/app-loader/AppLoader.tsx
  code/src/components/app-logo/AppLogo.tsx
  code/src/components/app-pagination/AppPagination.test.tsx
  code/src/components/app-snackbar/AppSnackbar.test.tsx
  code/src/components/app-typography/AppTypography.tsx
  code/src/components/product-card/ProductCard.test.tsx
  code/src/components/product-card/ProductCard.tsx
  code/src/layouts/best-sellers/BestSellers.test.tsx
  code/src/layouts/call-to-action/CallToAction.test.tsx
  code/src/layouts/call-to-action/components/call-to-action-item/CallToActionItem.test.tsx
  code/src/layouts/footer/Footer.test.tsx
  code/src/layouts/header/Header.test.tsx
  code/src/layouts/header/components/header-categories/HeaderCategories.test.tsx
  code/src/layouts/header/components/header-toolbar/HeaderToolbar.test.tsx
  code/src/layouts/modals/auth/AuthModal.test.tsx
  code/src/layouts/order-item/OrderItem.test.tsx
  code/src/layouts/order-item/OrderItem.tsx
  code/src/layouts/order-item/components/order-product-item/OrderProductItem.tsx
  code/src/layouts/page-loading-fallback/PageLoadingFallback.tsx
  code/src/layouts/protected-layout/ProtectedLayout.test.tsx
  code/src/layouts/root-layout/RootLayout.test.tsx
  code/src/pages/not-found/NotFoundPage.test.tsx
  code/src/store/api/ordersApi.ts
  code/src/store/api/productsApi.ts
  code/src/utils/cn/cn.test.ts
  code/src/utils/cn/cn.ts
  code/src/utils/create-url-path/createUrlPath.test.tsx
  code/src/utils/create-url-path/createUrlPath.ts
  code/src/utils/format-price/formatPrice.test.ts
  code/src/utils/format-price/formatPrice.ts
  code/src/utils/render-with-providers/renderWithProviders.tsx
Labels: feature, good first issue, frontend, refactor

#174 Fix error in console related to redux selectors
  code/src/layouts/header/components/header-toolbar/HeaderToolbar.test.tsx
  code/src/layouts/header/components/header-toolbar/HeaderToolbar.tsx
  code/src/layouts/protected-layout/ProtectedLayout.test.tsx
  code/src/layouts/protected-layout/ProtectedLayout.tsx
  code/src/store/slices/userSlice.ts
Labels: bug, priority:low, frontend, refactor

#168 Added forms validation
  code/package-lock.json
  code/package.json
  code/src/components/app-input/AppInput.tsx
  code/src/components/app-input/AppInput.types.ts
  code/src/constants/common-messages/en.json
  code/src/constants/requests.ts
  code/src/hooks/use-input-visibility/VisibilityIcon.scss
  code/src/hooks/use-input-visibility/useInputVisibility.test.ts
  code/src/hooks/use-input-visibility/useInputVisibility.tsx
  code/src/layouts/forms/sign-in-form/SignInForm.scss
  code/src/layouts/forms/sign-in-form/SignInForm.test.tsx
  code/src/layouts/forms/sign-in-form/SignInForm.tsx
  code/src/layouts/forms/sign-in-form/messages/en.json
  code/src/layouts/forms/sign-in-form/messages/index.ts
  code/src/layouts/forms/sign-in-form/messages/uk.json
  code/src/layouts/forms/sign-up-form/SignUpForm.scss
  code/src/layouts/forms/sign-up-form/SignUpForm.test.tsx
  code/src/layouts/forms/sign-up-form/SignUpForm.tsx
  code/src/layouts/forms/sign-up-form/messages/en.json
  code/src/layouts/forms/sign-up-form/messages/index.ts
  code/src/layouts/forms/sign-up-form/messages/uk.json
  code/src/layouts/modals/auth/AuthModal.scss
  code/src/layouts/modals/auth/AuthModal.test.tsx
  code/src/layouts/modals/auth/AuthModal.tsx
  code/src/layouts/modals/auth/components/login-form/LoginForm.test.tsx
  code/src/layouts/modals/auth/components/login-form/LoginForm.tsx
  code/src/layouts/modals/auth/components/login-form/messages/en.json
  code/src/layouts/modals/auth/components/login-form/messages/index.ts
  code/src/layouts/modals/auth/components/login-form/messages/uk.json
  code/src/layouts/modals/auth/components/signup-form/SignupForm.test.tsx
  code/src/layouts/modals/auth/components/signup-form/SignupForm.tsx
  code/src/layouts/modals/auth/components/signup-form/messages/en.json
  code/src/layouts/modals/auth/components/signup-form/messages/index.ts
  code/src/layouts/modals/auth/components/signup-form/messages/uk.json
  code/src/layouts/modals/auth/messages/en.json
  code/src/layouts/modals/auth/messages/uk.json
  code/src/messages.ts
  code/src/types/auth.types.ts
  code/src/utils/type-into-input/typeIntoInput.ts
  code/src/utils/validators/signInScheme.ts
  code/src/utils/validators/signUpScheme.ts
Labels: feature, frontend, sprint 2, auth

#161 Feature/86/skeleton for product items
  code/src/components/product-skeleton/ProductSkeleton.scss
  code/src/components/product-skeleton/ProductSkeleton.test.tsx
  code/src/components/product-skeleton/ProductSkeleton.tsx
  code/src/layouts/best-sellers/BestSellers.test.tsx
  code/src/layouts/best-sellers/BestSellers.tsx
  code/src/pages/products/ProductsPage.tsx
  code/src/utils/createSkeletonCards.tsx
  code/src/utils/tests/createSkeletonCards.test.tsx
Labels: frontend, ui

#182 Refactored check auth logic
  code/src/hooks/use-sign-in/useSignIn.test.ts
  code/src/hooks/use-sign-in/useSignIn.ts
  code/src/hooks/use-sign-up/useSignUp.test.ts
  code/src/hooks/use-sign-up/useSignUp.ts
  code/src/store/slices/userSlice.ts
  code/src/types/auth.types.ts
  code/src/types/user.types.ts
Labels: feature, frontend, auth

#187 Improved coverage for AppDropdown
  code/src/components/app-dropdown/AppDropdown.test.tsx
  code/src/components/app-dropdown/AppDropdown.tsx
Labels: frontend, tests

#192 Added favicon for the website
  code/config/index.html
  code/config/webpack.config.js
  code/package-lock.json
  code/package.json
  code/src/assets/icons/.gitkeep
  code/src/assets/icons/favicon.ico
  code/src/pages/products/ProductsPage.tsx
Labels: priority:low, feature, frontend

#186 Added tests
  code/src/layouts/best-sellers/BestSellers.test.tsx
  code/src/pages/error/ErrorPage.test.tsx
  code/src/pages/home/HomePage.test.tsx
  code/src/pages/orders/OrdersPage.test.tsx
  code/src/pages/products/ProductsPage.test.tsx
  code/src/pages/products/ProductsPage.tsx
  code/src/types/common.ts
  code/src/utils/validate-page/validatePage.test.ts
  code/src/utils/validate-page/validatePage.ts
Labels: frontend, tests

#195 Temporary hardcod baseUrl
  code/src/store/api/appApi.ts
Labels: frontend

#198 Fix coverage report for e2e tests
  .gitignore
  e2e/cypress/test_module/cypress.config.ts
  e2e/cypress/test_module/cypress/config/fix-cucumber-report.ts
  e2e/cypress/test_module/cypress/features/dashboard/dashboard.feature
  e2e/cypress/test_module/cypress/plugins/addWebpackPreprocessorPlugin.ts
  e2e/cypress/test_module/cypress/plugins/index.ts
  e2e/cypress/test_module/cypress/webpack.config.js
  e2e/cypress/test_module/package-lock.json
  e2e/cypress/test_module/package.json
  e2e/cypress/test_module/tsconfig.json
Labels: bug, frontend, priority:high, refactor, tests

#199 Refactor createProductSkeletons to more generic repeatComponent util
  code/src/layouts/best-sellers/BestSellers.tsx
  code/src/pages/products/ProductsPage.tsx
  code/src/utils/createSkeletonCards.tsx
  code/src/utils/repeat-component/repeatComponent.test.tsx
  code/src/utils/repeat-component/repeatComponent.tsx
  code/src/utils/tests/createSkeletonCards.test.tsx
Labels: priority:low, frontend, refactor

#203 Added badge variants
  code/src/components/app-badge/AppBadge.scss
  code/src/components/app-badge/AppBadge.types.ts
  code/src/components/app-snackbar/AppSnackbar.scss
  code/src/components/app-typography/AppTypography.scss
  code/src/constants/orderStatuses.ts
  code/src/layouts/order-item/OrderItem.constants.ts
  code/src/layouts/order-item/OrderItem.scss
  code/src/layouts/order-item/OrderItem.tsx
  code/src/layouts/order-item/OrderItems.types.ts
  code/src/styles/foundation/_variables.scss
  code/src/types/order.types.ts
Labels: feature, frontend, ui, design system, sprint 3

#206 Fixed all of the console warnings during tests run
  code/config/jest.config.js
  code/config/setup-tests.js
  code/src/hooks/use-sign-in/useSignIn.test.ts
  code/src/hooks/use-sign-up/useSignUp.test.ts
  code/src/layouts/header/components/header-toolbar/HeaderToolbar.test.tsx
  code/src/layouts/protected-layout/ProtectedLayout.test.tsx
  code/stryker.conf.js
Labels: frontend, tests, sprint 3

#205 Refactored ProtectedLayout into ProtectedRoute and added role protection to it
  code/src/layouts/protected-layout/ProtectedLayout.test.tsx
  code/src/layouts/protected-layout/ProtectedLayout.tsx
  code/src/routes/protected-route/ProtectedRoute.test.tsx
  code/src/routes/protected-route/ProtectedRoute.tsx
  code/src/routes/protectedRoutes.tsx
  code/src/routes/routes.tsx
  code/src/types/common.ts
  mock-backend/src/services/authService.js
Labels: feature, priority:medium, frontend, auth, sprint 3

#208 Created scroll to the top button
  code/src/App.tsx
  code/src/components/scroll-to-top-button/ScrollToTopButton.scss
  code/src/components/scroll-to-top-button/ScrollToTopButton.test.tsx
  code/src/components/scroll-to-top-button/ScrollToTopButton.tsx
Labels: feature, frontend, ui, sprint 3

#216 Add proper links to Shop buttons and fix naming of translation
  code/src/layouts/call-to-action/CallToAction.constants.ts
  code/src/layouts/call-to-action/components/call-to-action-item/CallToActionItem.test.tsx
  code/src/layouts/call-to-action/messages/en.json
  code/src/layouts/call-to-action/messages/uk.json
Labels: bug, priority:low, good first issue, frontend, sprint 3

#197 Feature/194/base commands cypress
  code/src/components/app-snackbar/AppSnackbar.tsx
  code/src/layouts/forms/sign-in-form/SignInForm.tsx
  code/src/layouts/forms/sign-up-form/SignUpForm.tsx
  code/src/layouts/header/components/header-toolbar/HeaderToolbar.tsx
  code/src/layouts/modals/auth/AuthModal.tsx
  e2e/cypress/test_module/cypress.config.ts
  e2e/cypress/test_module/cypress/fixtures/global-data.ts
  e2e/cypress/test_module/cypress/support/commands.ts
  e2e/cypress/test_module/cypress/support/index.ts
  e2e/cypress/test_module/package-lock.json
  e2e/cypress/test_module/package.json
  mock-backend/src/services/authService.js
Labels: frontend, priority:high, tests, sprint 3

#210 Added ProductsGrid component
  code/src/components/products-container/ProductsContainer.scss
  code/src/components/products-container/ProductsContainer.test.tsx
  code/src/components/products-container/ProductsContainer.tsx
  code/src/components/products-container/ProductsContainer.types.ts
  code/src/layouts/best-sellers/BestSellers.scss
  code/src/layouts/best-sellers/BestSellers.tsx
  code/src/pages/products/ProductsPage.scss
  code/src/pages/products/ProductsPage.test.tsx
  code/src/pages/products/ProductsPage.tsx
Labels: frontend, refactor

#217 Fixed flash and jumps for header icon loading
  code/src/layouts/header/components/header-toolbar/HeaderToolbar.test.tsx
  code/src/layouts/header/components/header-toolbar/HeaderToolbar.tsx
Labels: bug, frontend, sprint 3

#233 Added multiple env files
  README.md
  code/config/webpack.config.js
  code/config/webpack.development.config.js
  code/config/webpack.production.config.js
  code/config/webpack.test.config.js
  code/package.json
Labels: frontend, sprint 3

#237 Sync manager role with backend side
  code/src/constants/common.ts
  code/src/layouts/header/components/header-toolbar/HeaderToolbar.test.tsx
  code/src/layouts/header/components/header-toolbar/HeaderToolbar.tsx
  e2e/cypress/test_module/cypress/fixtures/global-data.ts
  mock-backend/src/services/authService.js
Labels: frontend, priority:high

#235 Created AppTable
  code/src/components/app-table/AppTable.test.tsx
  code/src/components/app-table/AppTable.tsx
  code/src/components/app-table/components/app-table-body/AppTableBody.test.tsx
  code/src/components/app-table/components/app-table-body/AppTableBody.tsx
  code/src/components/app-table/components/app-table-body/AppTableBody.types.ts
  code/src/components/app-table/components/app-table-box/AppTableBox.test.tsx
  code/src/components/app-table/components/app-table-box/AppTableBox.tsx
  code/src/components/app-table/components/app-table-box/AppTableBox.types.ts
  code/src/components/app-table/components/app-table-cell/AppTableCell.test.tsx
  code/src/components/app-table/components/app-table-cell/AppTableCell.tsx
  code/src/components/app-table/components/app-table-cell/AppTableCell.types.ts
  code/src/components/app-table/components/app-table-container/AppTableContainer.scss
  code/src/components/app-table/components/app-table-container/AppTableContainer.test.tsx
  code/src/components/app-table/components/app-table-container/AppTableContainer.tsx
  code/src/components/app-table/components/app-table-container/AppTableContainer.types.ts
  code/src/components/app-table/components/app-table-head/AppTableHead.test.tsx
  code/src/components/app-table/components/app-table-head/AppTableHead.tsx
  code/src/components/app-table/components/app-table-head/AppTableHead.types.ts
  code/src/components/app-table/components/app-table-row/AppTableRow.test.tsx
  code/src/components/app-table/components/app-table-row/AppTableRow.tsx
  code/src/components/app-table/components/app-table-row/AppTableRow.types.ts
  code/src/components/app-table/components/index.tsx
  code/src/routes/protectedRoutes.tsx
  mock-backend/src/app.js
Labels: feature, frontend, ui, sprint 3, dashboard

#241 Created view for cart with route
  code/src/constants/routes.ts
  code/src/messages.ts
  code/src/pages/cart/CartPage.constants.tsx
  code/src/pages/cart/CartPage.scss
  code/src/pages/cart/CartPage.testt.tsx
  code/src/pages/cart/CartPage.tsx
  code/src/pages/cart/components/CartItem.scss
  code/src/pages/cart/components/CartItem.testt.tsx
  code/src/pages/cart/components/CartItem.tsx
  code/src/pages/cart/messages/en.json
  code/src/pages/cart/messages/index.ts
  code/src/pages/cart/messages/uk.json
  code/src/routes/guestRoutes.tsx
Labels: feature, frontend, priority:high, sprint 3

#243 Created cart drawer
  code/src/components/product-card/ProductCard.scss
  code/src/components/product-card/ProductCard.test.tsx
  code/src/components/product-card/ProductCard.tsx
  code/src/components/product-card/ProductCard.types.ts
  code/src/components/products-container/ProductsContainer.tsx
  code/src/context/DrawerContext.tsx
  code/src/layouts/cart-drawer/CartDrawer.scss
  code/src/layouts/cart-drawer/CartDrawer.tsx
  code/src/layouts/cart-drawer/cart-drawer-item/CartDrawerItem.scss
  code/src/layouts/cart-drawer/cart-drawer-item/CartDrawerItem.tsx
  code/src/layouts/cart-drawer/constants.ts
  code/src/layouts/cart-drawer/message/en.json
  code/src/layouts/cart-drawer/message/index.ts
  code/src/layouts/cart-drawer/message/uk.json
  code/src/layouts/header/components/header-toolbar/HeaderToolbar.tsx
  code/src/layouts/root-layout/RootLayout.tsx
  code/src/main.tsx
  code/src/messages.ts
  code/src/types/Cart.types.ts
  code/src/utils/render-with-providers/renderWithProviders.tsx
Labels: feature, frontend, sprint 3

#238 Created orders table
  code/src/components/app-table/AppTable.tsx
  code/src/components/app-table/components/app-table-container/AppTableContainer.scss
  code/src/constants/common-messages/en.json
  code/src/constants/common-messages/uk.json
  code/src/constants/orderStatuses.ts
  code/src/layouts/order-item/OrderItem.constants.ts
  code/src/layouts/order-item/OrderItem.tsx
  code/src/layouts/order-item/OrderItems.types.ts
  code/src/layouts/orders-list/OrdersList.test.tsx
  code/src/layouts/tables/orders-table/OrdersTable.constants.ts
  code/src/layouts/tables/orders-table/OrdersTable.scss
  code/src/layouts/tables/orders-table/OrdersTable.test.tsx
  code/src/layouts/tables/orders-table/OrdersTable.tsx
  code/src/layouts/tables/orders-table/components/orders-table-body/OrdersTableBody.scss
  code/src/layouts/tables/orders-table/components/orders-table-body/OrdersTableBody.test.tsx
  code/src/layouts/tables/orders-table/components/orders-table-body/OrdersTableBody.tsx
  code/src/layouts/tables/orders-table/components/orders-table-head/OrdersTableHead.scss
  code/src/layouts/tables/orders-table/components/orders-table-head/OrdersTableHead.test.tsx
  code/src/layouts/tables/orders-table/components/orders-table-head/OrdersTableHead.tsx
  code/src/layouts/tables/orders-table/messages/en.json
  code/src/layouts/tables/orders-table/messages/index.ts
  code/src/layouts/tables/orders-table/messages/uk.json
  code/src/messages.ts
Labels: feature, frontend, ui, design system, sprint 3, dashboard

#240 Add admin dashboard tabs
  code/src/layouts/dashboard-tabs/DashboardTabs.constants.tsx
  code/src/layouts/dashboard-tabs/DashboardTabs.scss
  code/src/layouts/dashboard-tabs/DashboardTabs.test.tsx
  code/src/layouts/dashboard-tabs/DashboardTabs.tsx
  code/src/layouts/dashboard-tabs/components/dashboard-tab/DashboardTab.test.tsx
  code/src/layouts/dashboard-tabs/components/dashboard-tab/DashboardTab.tsx
  code/src/layouts/dashboard-tabs/components/orders-tab/OrderTab.test.tsx
  code/src/layouts/dashboard-tabs/components/orders-tab/OrdersTab.tsx
  code/src/layouts/dashboard-tabs/components/products-tab/ProductsTab.test.tsx
  code/src/layouts/dashboard-tabs/components/products-tab/ProductsTab.tsx
  code/src/layouts/dashboard-tabs/components/users-tab/UsersTab.test.tsx
  code/src/layouts/dashboard-tabs/components/users-tab/UsersTab.tsx
  code/src/layouts/dashboard-tabs/messages/en.json
  code/src/layouts/dashboard-tabs/messages/index.ts
  code/src/layouts/dashboard-tabs/messages/uk.json
  code/src/messages.ts
  code/src/pages/dashboard/DashboardPage.scss
  code/src/pages/dashboard/DashboardPage.test.tsx
  code/src/pages/dashboard/DashboardPage.tsx
  code/src/styles/foundation/_variables.scss
  code/src/types/common.ts
  code/src/types/user.types.ts
Labels: feature, priority:medium, frontend, ui, sprint 3, dashboard

#244 Add tests for ModalContext
  code/src/context/modal/ModalContext.test.tsx
  code/src/context/modal/ModalContext.tsx
  code/src/layouts/forms/sign-in-form/SignInForm.test.tsx
  code/src/layouts/forms/sign-in-form/SignInForm.tsx
  code/src/layouts/forms/sign-up-form/SignUpForm.test.tsx
  code/src/layouts/forms/sign-up-form/SignUpForm.tsx
  code/src/layouts/header/components/header-toolbar/HeaderToolbar.tsx
  code/src/layouts/modals/auth/AuthModal.tsx
  code/src/layouts/root-layout/RootLayout.tsx
  code/src/utils/render-with-providers/renderWithProviders.tsx
Labels: priority:low, frontend, tests, sprint 3

#250 Increase test coverage (App.tsx, useRedux.ts, AppButton, AppInput)
  code/src/App.test.tsx
  code/src/components/app-button/AppButton.test.tsx
  code/src/components/app-input/AppInput.test.tsx
  code/src/hooks/use-redux/useRedux.test.tsx
Labels: priority:low, frontend, tests, sprint 3

#252 Set default value for product sort param
  code/src/pages/products/ProductsPage.test.tsx
  code/src/pages/products/ProductsPage.tsx
Labels: bug, priority:low, frontend, sprint 3

#248 Added ability to delete and add product to the cart
  code/src/components/products-container/ProductsContainer.test.tsx
  code/src/components/products-container/ProductsContainer.tsx
  code/src/constants/api-tags.ts
  code/src/constants/common-messages/en.json
  code/src/constants/common-messages/uk.json
  code/src/constants/requests.ts
  code/src/layouts/best-sellers/BestSellers.test.tsx
  code/src/layouts/cart-drawer/CartDrawer.tsx
  code/src/layouts/cart-drawer/cart-drawer-item/CartDrawerItem.tsx
  code/src/layouts/cart-drawer/cart-drawer-item/CartDrawerItem.types.ts
  code/src/pages/products/ProductsPage.test.tsx
  code/src/store/api/appApi.ts
  code/src/store/api/cartApi.ts
  code/src/types/cart.types.ts
  mock-backend/src/app.js
  mock-backend/src/controllers/authController.js
  mock-backend/src/controllers/cartController.js
  mock-backend/src/routes/cartRoutes.js
Labels: feature, frontend, sprint 3

#247 Added redirect to products in the home page
  code/src/components/product-card/ProductCard.tsx
  code/src/layouts/best-sellers/BestSellers.test.tsx
  code/src/layouts/best-sellers/BestSellers.tsx
  code/src/layouts/intro-banner/IntroBanner.test.tsx
  code/src/layouts/intro-banner/IntroBanner.tsx
Labels: priority:low, feature, frontend, sprint 3

#253 Refactor orders type
  code/src/layouts/order-item/OrderItem.scss
  code/src/layouts/order-item/OrderItem.test.tsx
  code/src/layouts/order-item/OrderItem.tsx
  code/src/layouts/order-item/components/order-item-details/OrderItemDetails.scss
  code/src/layouts/order-item/components/order-item-details/OrderItemDetails.tsx
  code/src/layouts/order-item/components/order-item-details/OrderProductDetails.test.tsx
  code/src/layouts/order-item/components/order-product-item/OrderProductItem.scss
  code/src/layouts/order-item/components/order-product-item/OrderProductItem.test.tsx
  code/src/layouts/order-item/components/order-product-item/OrderProductItem.tsx
  code/src/layouts/order-item/messages/en.json
  code/src/layouts/order-item/messages/uk.json
  code/src/layouts/orders-list/OrdersList.test.tsx
  code/src/layouts/orders-list/OrdersList.tsx
  code/src/layouts/tables/orders-table/OrdersTable.constants.ts
  code/src/layouts/tables/orders-table/OrdersTable.test.tsx
  code/src/layouts/tables/orders-table/OrdersTable.tsx
  code/src/layouts/tables/orders-table/components/orders-table-body/OrdersTableBody.test.tsx
  code/src/layouts/tables/orders-table/components/orders-table-body/OrdersTableBody.tsx
  code/src/store/api/ordersApi.ts
  code/src/types/order.types.ts
  mock-backend/src/data/mokedOrders.js
Labels: frontend, refactor, ui, sprint 3

#261 Revert webpack npm scripts
  code/package.json
Labels: bug, priority:high

#258 Added get orders for dashboard
  code/src/components/app-table/AppTable.test.tsx
  code/src/components/app-table/AppTable.tsx
  code/src/components/app-table/AppTable.types.ts
  code/src/constants/requests.ts
  code/src/containers/call-to-action/CallToAction.scss
  code/src/containers/dashboard-tabs/DashboardTabs.scss
  code/src/containers/dashboard-tabs/components/orders-tab/OrderTab.test.tsx
  code/src/containers/dashboard-tabs/components/orders-tab/OrdersTab.test.tsx
  code/src/containers/dashboard-tabs/components/orders-tab/OrdersTab.tsx
  code/src/containers/dashboard-tabs/components/tab-container/TabContainer.scss
  code/src/containers/dashboard-tabs/components/tab-container/TabContainer.test.tsx
  code/src/containers/dashboard-tabs/components/tab-container/TabContainer.tsx
  code/src/containers/dashboard-tabs/messages/en.json
  code/src/containers/dashboard-tabs/messages/uk.json
  code/src/containers/tables/orders-table/OrdersTable.constants.ts
  code/src/containers/tables/orders-table/OrdersTable.scss
  code/src/containers/tables/orders-table/OrdersTable.test.tsx
  code/src/containers/tables/orders-table/OrdersTable.tsx
  code/src/containers/tables/orders-table/components/orders-table-body/OrdersTableBody.test.tsx
  code/src/containers/tables/orders-table/components/orders-table-head/OrdersTableHead.test.tsx
  code/src/containers/tables/orders-table/messages/en.json
  code/src/containers/tables/orders-table/messages/uk.json
  code/src/layouts/page-wrapper/PageWrapper.scss
  code/src/pages/orders/OrdersPage.test.tsx
  code/src/pages/orders/OrdersPage.tsx
  code/src/store/api/ordersApi.ts
  code/src/store/slices/userSlice.ts
  code/src/types/order.types.ts
  code/src/types/user.types.ts
  mock-backend/src/controllers/orderConroller.js
  mock-backend/src/data/mokedOrders.js
  mock-backend/src/routes/orderRoutes.js
Labels: feature, frontend, sprint 3, dashboard

#259 Created logic for get products for cart of current user
  code/src/components/order-summary/OrderSummary.scss
  code/src/components/order-summary/OrderSummary.test.tsx
  code/src/components/order-summary/OrderSummary.tsx
  code/src/constants/requests.ts
  code/src/pages/cart/CartPage.constants.tsx
  code/src/pages/cart/CartPage.scss
  code/src/pages/cart/CartPage.test.tsx
  code/src/pages/cart/CartPage.testt.tsx
  code/src/pages/cart/CartPage.tsx
  code/src/pages/cart/components/CartItem.test.tsx
  code/src/pages/cart/components/CartItem.testt.tsx
  code/src/pages/cart/components/CartItem.tsx
  code/src/pages/cart/messages/en.json
  code/src/pages/cart/messages/uk.json
  code/src/store/api/cartApi.ts
  code/src/types/cart.types.ts
  code/src/types/user.types.ts
  mock-backend/src/controllers/cartController.js
  mock-backend/src/data/mockedCartItems.js
  mock-backend/src/routes/cartRoutes.js
Labels: feature, frontend, sprint 3

#271 Added production env to dockerfile
  code/Dockerfile
Labels: bug, frontend, sprint 3

#270 Created useGetUserDetails hook
  code/src/constants/requests.ts
  code/src/containers/order-item/OrderItem.test.tsx
  code/src/hooks/use-get-user-details/useGetUserDetails.test.ts
  code/src/hooks/use-get-user-details/useGetUserDetails.ts
  code/src/pages/cart/CartPage.test.tsx
  code/src/pages/cart/CartPage.tsx
  code/src/pages/orders/OrdersPage.test.tsx
  code/src/pages/orders/OrdersPage.tsx
  code/src/routes/guestRoutes.tsx
  code/src/routes/protectedRoutes.tsx
  code/src/store/api/cartApi.ts
  code/src/store/api/ordersApi.ts
  code/src/types/cart.types.ts
  code/src/types/order.types.ts
  code/src/types/user.types.ts
Labels: feature, frontend, auth, sprint 3, dashboard

#275 Added tests for drawer context
  code/src/containers/best-sellers/BestSellers.tsx
  code/src/containers/cart-drawer/CartDrawer.tsx
  code/src/containers/products-container/ProductsContainer.scss
  code/src/containers/products-container/ProductsContainer.test.tsx
  code/src/containers/products-container/ProductsContainer.tsx
  code/src/containers/products-container/ProductsContainer.types.ts
  code/src/context/drawer/DrawerContext.test.tsx
  code/src/context/drawer/DrawerContext.tsx
  code/src/layouts/header/components/header-toolbar/HeaderToolbar.tsx
  code/src/layouts/root-layout/RootLayout.tsx
  code/src/pages/products/ProductsPage.tsx
  code/src/utils/render-with-providers/renderWithProviders.tsx
Labels: frontend, tests, sprint 3

#175 Tests/165/add integration tests for user home page
  code/src/components/product-card/ProductCard.tsx
  code/src/components/product-skeleton/ProductSkeleton.tsx
  code/src/containers/best-sellers/BestSellers.tsx
  code/src/containers/call-to-action/CallToAction.tsx
  code/src/containers/call-to-action/components/call-to-action-item/CallToActionItem.tsx
  code/src/containers/cart-drawer/CartDrawer.tsx
  code/src/containers/category-section/CategorySection.tsx
  code/src/containers/intro-banner/IntroBanner.tsx
  code/src/containers/modals/auth/AuthModal.tsx
  code/src/containers/products-container/ProductsContainer.tsx
  code/src/containers/subintro/Subintro.tsx
  code/src/layouts/footer/Footer.tsx
  code/src/layouts/header/components/header-toolbar/HeaderToolbar.tsx
  code/src/pages/dashboard/DashboardPage.tsx
  code/src/pages/products/ProductsPage.tsx
  e2e/cypress/test_module/cypress/features/auth/logout.feature
  e2e/cypress/test_module/cypress/features/auth/sign-in.feature
  e2e/cypress/test_module/cypress/features/auth/sign-up.feature
  e2e/cypress/test_module/cypress/features/dashboard/dashboard.feature
  e2e/cypress/test_module/cypress/features/header/header.feature
  e2e/cypress/test_module/cypress/features/home-page/home-page-general.feature
  e2e/cypress/test_module/cypress/features/home-page/home-page-manager.feature
  e2e/cypress/test_module/cypress/features/home-page/home-page-user.feature
  e2e/cypress/test_module/cypress/features/products-page/products-page.feature
  e2e/cypress/test_module/cypress/fixtures/global-data.ts
  e2e/cypress/test_module/cypress/support/commands.ts
  e2e/cypress/test_module/cypress/support/index.ts
  e2e/cypress/test_module/cypress/support/page-objects/dashboard-page.ts
  e2e/cypress/test_module/cypress/support/page_objects/home-pages.ts
  e2e/cypress/test_module/cypress/support/step_definitions/auth.steps.ts
  e2e/cypress/test_module/cypress/support/step_definitions/common.steps.ts
  e2e/cypress/test_module/cypress/support/step_definitions/header.steps.ts
  e2e/cypress/test_module/cypress/support/step_definitions/home-page-general.steps.ts
  e2e/cypress/test_module/cypress/support/step_definitions/home-page-manager.steps.ts
  e2e/cypress/test_module/cypress/support/step_definitions/home-page-user.steps.ts
  e2e/cypress/test_module/cypress/support/step_definitions/logout.steps.ts
  e2e/cypress/test_module/cypress/support/step_definitions/products-page.steps.ts
  e2e/cypress/test_module/cypress/support/step_definitions/sign-in.steps.ts
  e2e/cypress/test_module/cypress/support/step_definitions/sign-up.steps.ts
  e2e/cypress/test_module/tsconfig.json
Labels: tests

#274 Added real cart items counter to header cart icon
  code/src/layouts/header/components/header-toolbar/HeaderToolbar.test.tsx
  code/src/layouts/header/components/header-toolbar/HeaderToolbar.tsx
  code/src/store/api/cartApi.ts
Labels: feature, frontend, sprint 3

#277 Tests for snackbar slice
  code/src/store/slices/snackbarSlice.test.tsx
  code/src/store/slices/snackbarSlice.ts
Labels: tests

#281 Created Footer Banner
  code/src/assets/images/footer/footer-banner-bg.webp
  code/src/assets/images/footer/footer-banner.webp
  code/src/assets/images/home-page/subintro/box-icon.jpg
  code/src/assets/images/home-page/subintro/clock-icon.jpg
  code/src/assets/images/home-page/subintro/moped-icon.jpg
  code/src/assets/images/home-page/subintro/percent-icon.jpg
  code/src/containers/subintro/Subintro.constants.ts
  code/src/layouts/footer/Footer.scss
  code/src/layouts/footer/Footer.test.tsx
  code/src/layouts/footer/Footer.tsx
  code/src/layouts/footer/components/footer-banner/FooterBanner.scss
  code/src/layouts/footer/components/footer-banner/FooterBanner.test.tsx
  code/src/layouts/footer/components/footer-banner/FooterBanner.tsx
  code/src/layouts/footer/messages/en.json
  code/src/layouts/footer/messages/uk.json
  code/src/layouts/page-wrapper/PageWrapper.scss
Labels: feature, frontend, ui, sprint 3

#279 Added access rules for toolbar icons / Added more mock products
  code/src/layouts/header/components/header-toolbar/HeaderToolbar.test.tsx
  code/src/layouts/header/components/header-toolbar/HeaderToolbar.tsx
  mock-backend/src/controllers/productController.js
  mock-backend/src/data/mokedData.js
Labels: feature, frontend

#284 Add AppRangeSlider component
  code/src/components/app-range-slider/AppRangeSlider.scss
  code/src/components/app-range-slider/AppRangeSlider.test.tsx
  code/src/components/app-range-slider/AppRangeSlider.tsx
  code/src/components/app-range-slider/AppRangeSlider.types.ts
  code/src/constants/common-messages/en.json
  code/src/constants/common-messages/uk.json
Labels: feature, priority:medium, frontend, design system, sprint 3

#287 Add AppCheckbox component
  code/src/components/app-checkbox/AppCheckbox.scss
  code/src/components/app-checkbox/AppCheckbox.test.tsx
  code/src/components/app-checkbox/AppCheckbox.tsx
  code/src/components/app-checkbox/AppCheckbox.types.ts
Labels: feature, frontend, ui, design system, sprint 3

#280 Changed product card "add to cart" logic
  code/src/assets/icons/cart-with-check.svg
  code/src/assets/icons/cart-with-plus.svg
  code/src/components/product-card/ProductCard.scss
  code/src/components/product-card/ProductCard.test.tsx
  code/src/components/product-card/ProductCard.tsx
  code/src/components/product-card/ProductCard.types.ts
  code/src/containers/best-sellers/BestSellers.test.tsx
  code/src/containers/products-container/ProductsContainer.test.tsx
  code/src/containers/products-container/ProductsContainer.tsx
  code/src/containers/products-container/ProductsContainer.types.ts
  code/src/pages/products/ProductsPage.test.tsx
  mock-backend/src/controllers/cartController.js
Labels: feature, frontend, sprint 3

#289 Added logic to get items via drower and to remove on both places
  code/src/containers/cart-drawer/CartDrawer.tsx
  code/src/containers/cart-drawer/cart-drawer-item/CartDrawerItem.tsx
  code/src/containers/cart-drawer/cart-drawer-item/CartDrawerItem.types.ts
  code/src/containers/cart-drawer/constants.ts
  code/src/containers/cart-drawer/message/en.json
  code/src/containers/cart-drawer/message/uk.json
  code/src/hooks/use-cart-items/useUserCartItems.test.ts
  code/src/hooks/use-cart-items/useUserCartItems.ts
  code/src/pages/cart/CartPage.test.tsx
  code/src/pages/cart/CartPage.tsx
  code/src/pages/cart/components/CartItem.test.tsx
  code/src/pages/cart/components/CartItem.tsx
  code/src/types/cart.types.ts
Labels: feature, frontend, sprint 3

#295 App Select
  code/src/components/app-menu-item/AppMenuItem.test.tsx
  code/src/components/app-menu-item/AppMenuItem.tsx
  code/src/components/app-menu-item/AppMenuItem.types.ts
  code/src/components/app-select/AppSelect.scss
  code/src/components/app-select/AppSelect.test.tsx
  code/src/components/app-select/AppSelect.tsx
  code/src/components/app-select/AppSelect.types.ts
  code/src/styles/global.scss
Labels: feature, frontend, ui, design system, sprint 3

#291 Dashboard order filter drawer (UI only)
  code/src/assets/images/dashboard/nova-posta.webp
  code/src/assets/images/dashboard/ukr-posta.webp
  code/src/components/app-checkbox/AppCheckbox.scss
  code/src/components/app-checkbox/AppCheckbox.tsx
  code/src/components/app-checkbox/AppCheckbox.types.ts
  code/src/components/app-range-slider/AppRangeSlider.scss
  code/src/components/app-typography/AppTypography.types.ts
  code/src/constants/deliveryMethods.ts
  code/src/containers/dashboard-tabs/components/filter-record-accordion/FilterAccordion.types.ts
  code/src/containers/dashboard-tabs/components/filter-record-accordion/FilterRecordAccordion.scss
  code/src/containers/dashboard-tabs/components/filter-record-accordion/FilterRecordAccordion.tsx
  code/src/containers/dashboard-tabs/components/orders-tab-filter-drawer/OrdersTabFilterDrawer.scss
  code/src/containers/dashboard-tabs/components/orders-tab-filter-drawer/OrdersTabFilterDrawer.test.tsx
  code/src/containers/dashboard-tabs/components/orders-tab-filter-drawer/OrdersTabFilterDrawer.tsx
  code/src/containers/dashboard-tabs/components/orders-tab/OrdersTab.scss
  code/src/containers/dashboard-tabs/components/orders-tab/OrdersTab.test.tsx
  code/src/containers/dashboard-tabs/components/orders-tab/OrdersTab.tsx
  code/src/containers/dashboard-tabs/messages/en.json
  code/src/containers/dashboard-tabs/messages/uk.json
  code/src/pages/dashboard/DashboardPage.scss
Labels: feature, frontend, sprint 3, dashboard

#290 Change product skeleton style
  code/src/components/product-skeleton/ProductSkeleton.scss
  code/src/components/product-skeleton/ProductSkeleton.test.tsx
  code/src/components/product-skeleton/ProductSkeleton.tsx
  code/src/pages/cart/CartPage.test.tsx
  code/src/pages/cart/CartPage.tsx
Labels: bug, frontend

#306 Change arrow icon for drawer
  code/src/containers/cart-drawer/CartDrawer.tsx
Labels: bug, frontend, ui, sprint 3

#305 Order invalidate tags
  code/src/constants/api-tags.ts
  code/src/constants/requests.ts
  code/src/main.tsx
  code/src/store/api/ordersApi.ts
Labels: bug, frontend, sprint 3

#309 Make cart icon visible only under role ROLE_USER in header toolbar
  code/src/layouts/header/components/header-toolbar/HeaderToolbar.test.tsx
  code/src/layouts/header/components/header-toolbar/HeaderToolbar.tsx
Labels: bug, frontend, sprint 3

#311 (to revert) Hide some elements temporarily before demo
  code/src/containers/dashboard-tabs/components/orders-tab/OrdersTab.test.tsx
  code/src/containers/dashboard-tabs/components/orders-tab/OrdersTab.tsx
  code/src/layouts/header/components/header-toolbar/HeaderToolbar.scss
  code/src/layouts/header/components/header-toolbar/HeaderToolbar.test.tsx
  code/src/layouts/header/components/header-toolbar/HeaderToolbar.tsx
  code/src/pages/cart/components/CartItem.test.tsx
  code/src/pages/cart/components/CartItem.tsx
Labels: priority:high

#300 Added ability to change order status
  code/src/components/app-select/AppSelect.tsx
  code/src/components/app-select/AppSelect.types.ts
  code/src/constants/api-tags.ts
  code/src/constants/requests.ts
  code/src/containers/dashboard-tabs/components/orders-tab/OrdersTab.test.tsx
  code/src/containers/tables/orders-table/OrdersTable.test.tsx
  code/src/containers/tables/orders-table/OrdersTable.tsx
  code/src/containers/tables/orders-table/components/orders-table-body/OrdersTableBody.scss
  code/src/containers/tables/orders-table/components/orders-table-body/OrdersTableBody.test.tsx
  code/src/containers/tables/orders-table/components/orders-table-body/OrdersTableBody.tsx
  code/src/store/api/ordersApi.ts
  code/src/types/order.types.ts
  mock-backend/src/controllers/orderConroller.js
  mock-backend/src/routes/orderRoutes.js
Labels: frontend, sprint 3

#312 Improved coverage
  code/src/containers/cart-drawer/CartDrawer.test.tsx
  code/src/containers/cart-drawer/CartDrawer.tsx
  code/src/containers/cart-drawer/cart-drawer-item/CartDrawerItem.test.tsx
  code/src/containers/cart-drawer/cart-drawer-item/CartDrawerItem.tsx
  code/src/hooks/use-add-to-cart/useAddToCart.test.ts
  code/src/hooks/use-get-cart/useGetCart.test.ts
  code/src/hooks/use-remove-from-cart/useRemoveFromCart.test.ts
  code/src/utils/get-local-storage-cart/getLocalStorageCart.test.ts
  code/src/utils/is-error-with-status/isErrorWithStatus.test.ts
  code/src/utils/set-local-storage-cart/setLocalStorageCart.test.ts
Labels: frontend, tests, sprint 3

#314 Header toolbar and e2e tests fixes
  code/src/layouts/header/components/header-toolbar/HeaderToolbar.test.tsx
  code/src/layouts/header/components/header-toolbar/HeaderToolbar.tsx
  e2e/cypress/test_module/cypress/features/home-page/home-page-general.feature
  e2e/cypress/test_module/cypress/support/page_objects/home-pages.ts
Labels: bug, priority:high

#325 Add beforeEach to App.test.tsx
  code/src/App.test.tsx
Labels: frontend, refactor, tests

#263 e2e tests for products page
  code/src/components/app-dropdown/components/AppDropdownOptions.tsx
  code/src/components/app-pagination/AppPagination.tsx
  code/src/components/product-card/ProductCard.tsx
  code/src/containers/products-container/ProductsContainer.tsx
  code/src/pages/products/ProductsPage.tsx
  e2e/cypress/test_module/cypress/features/products-page/products-page.feature
  e2e/cypress/test_module/cypress/fixtures/constants.ts
  e2e/cypress/test_module/cypress/fixtures/routes.ts
  e2e/cypress/test_module/cypress/support/commands.ts
  e2e/cypress/test_module/cypress/support/step_definitions/home-page-general.steps.ts
  e2e/cypress/test_module/cypress/support/step_definitions/products-page.steps.ts
Labels: frontend, tests, sprint 3

#334 Language selector
  code/src/assets/icons/en.svg
  code/src/assets/icons/uk.svg
  code/src/components/app-select/AppSelect.test.tsx
  code/src/components/app-select/AppSelect.tsx
  code/src/components/app-select/AppSelect.types.ts
  code/src/constants/common-messages/en.json
  code/src/constants/common-messages/uk.json
  code/src/constants/common.ts
  code/src/constants/locales.ts
  code/src/containers/language-select/LanguageSelect.scss
  code/src/containers/language-select/LanguageSelect.test.tsx
  code/src/containers/language-select/LanguageSelect.tsx
  code/src/containers/order-item/OrderItem.scss
  code/src/containers/subintro/messages/uk.json
  code/src/containers/tables/orders-table/components/orders-table-body/OrdersTableBody.tsx
  code/src/context/I18nProvider.tsx
  code/src/layouts/header/components/header-toolbar/HeaderToolbar.tsx
  code/src/main.tsx
  code/src/messages.ts
  code/src/utils/render-with-providers/renderWithProviders.tsx
Labels: feature, frontend, sprint 4

#327 Add tests to cart drawer
  code/src/containers/cart-drawer/CartDrawer.test.tsx
  code/src/containers/cart-drawer/CartDrawer.tsx
  code/src/hooks/use-cart-items/useUserCartItems.test.ts
  code/src/hooks/use-cart-items/useUserCartItems.ts
  code/src/pages/cart/CartPage.test.tsx
  code/src/pages/cart/CartPage.tsx
Labels: tests

#340 Improved coverage for for components and utils
  code/src/components/app-checkbox/AppCheckbox.test.tsx
  code/src/components/app-range-slider/AppRangeSlider.test.tsx
  code/src/components/app-select/AppSelect.test.tsx
  code/src/components/app-select/AppSelect.tsx
  code/src/components/app-table/AppTable.test.tsx
  code/src/components/app-table/AppTable.tsx
  code/src/components/product-card/ProductCard.test.tsx
  code/src/components/product-card/ProductCard.tsx
  code/src/utils/get-local-storage-cart/getLocalStorageCart.test.ts
  code/src/utils/is-error-with-status/isErrorWithStatus.test.ts
Labels: tests, sprint 4

#343 Added test for i18nProvider
  code/src/constants/locales.ts
  code/src/containers/language-select/LanguageSelect.tsx
  code/src/context/i18n/I18nProvider.test.tsx
  code/src/context/i18n/I18nProvider.tsx
  code/src/main.tsx
  code/src/messages.ts
  code/src/utils/render-with-providers/renderWithProviders.tsx
Labels: frontend, tests, sprint 4

#342 Improve tests for ProductsContainer and refactor BestSellers and ProductsPage tests
  code/src/containers/best-sellers/BestSellers.constants.ts
  code/src/containers/best-sellers/BestSellers.test.tsx
  code/src/containers/products-container/ProductContainer.constants.ts
  code/src/containers/products-container/ProductsContainer.test.tsx
  code/src/containers/products-container/ProductsContainer.tsx
  code/src/pages/products/ProductsPage.test.tsx
Labels: tests

#344 Added autocomplete attributes, fixed console warning
  code/src/containers/forms/sign-in-form/SignInForm.tsx
  code/src/containers/forms/sign-up-form/SignUpForm.tsx
Labels: bug, frontend

#346 Delivery form
  code/src/components/app-select/AppSelect.tsx
  code/src/components/app-select/AppSelect.types.ts
  code/src/constants/deliveryMethods.ts
  code/src/containers/forms/delivery-form/DeliveryForm.scss
  code/src/containers/forms/delivery-form/DeliveryForm.test.tsx
  code/src/containers/forms/delivery-form/DeliveryForm.tsx
  code/src/containers/forms/delivery-form/messages/en.json
  code/src/containers/forms/delivery-form/messages/index.ts
  code/src/containers/forms/delivery-form/messages/uk.json
  code/src/containers/order-summary/OrderSummary.test.tsx
  code/src/containers/order-summary/OrderSummary.tsx
  code/src/messages.ts
  code/src/pages/cart/CartPage.tsx
  code/src/types/delivery.types.ts
  code/src/utils/validators/deliveryScheme.ts
Labels: feature, frontend, sprint 4

#347 Increased containers coverage
  code/src/containers/forms/sign-up-form/SignUpForm.test.tsx
  code/src/containers/language-select/LanguageSelect.test.tsx
  code/src/containers/products-container/ProductsContainer.tsx
  code/src/containers/tables/orders-table/OrdersTable.test.tsx
  code/src/containers/tables/orders-table/components/orders-table-body/OrdersTableBody.test.tsx
  code/src/containers/tables/orders-table/components/orders-table-body/OrdersTableBody.tsx
  code/src/utils/get-local-storage-cart/getLocalStorageCart.test.ts
  code/src/utils/set-local-storage-cart/setLocalStorageCart.test.ts
Labels: tests, sprint 4

#301 Add filtration for orders on admin dashboard
  code/src/components/app-drawer/AppDrawer.test.tsx
  code/src/components/app-drawer/AppDrawer.tsx
  code/src/components/app-drawer/AppDrawer.types.ts
  code/src/components/app-icon-button/AppIconButton.tsx
  code/src/components/app-select/AppSelect.tsx
  code/src/components/app-tooltip/AppTooltip.tsx
  code/src/components/app-tooltip/AppTooltip.types.tsx
  code/src/constants/common-messages/en.json
  code/src/constants/common-messages/uk.json
  code/src/constants/deliveryMethods.ts
  code/src/constants/requests.ts
  code/src/constants/timeSpans.ts
  code/src/containers/dashboard-tabs/components/filter-record-accordion/FilterAccordion.types.ts
  code/src/containers/dashboard-tabs/components/filter-record-accordion/FilterRecordAccordion.scss
  code/src/containers/dashboard-tabs/components/filter-record-accordion/FilterRecordAccordion.tsx
  code/src/containers/dashboard-tabs/components/orders-tab-filter-drawer/OrdersTabFilterDrawer.scss
  code/src/containers/dashboard-tabs/components/orders-tab-filter-drawer/OrdersTabFilterDrawer.test.tsx
  code/src/containers/dashboard-tabs/components/orders-tab-filter-drawer/OrdersTabFilterDrawer.tsx
  code/src/containers/dashboard-tabs/components/orders-tab/OrdersTab.test.tsx
  code/src/containers/dashboard-tabs/components/orders-tab/OrdersTab.tsx
  code/src/containers/dashboard-tabs/hooks/use-filtered-admin-orders/useFilteredAdminOrders.constants.ts
  code/src/containers/dashboard-tabs/hooks/use-filtered-admin-orders/useFilteredAdminOrders.ts
  code/src/containers/dashboard-tabs/hooks/use-filtered-admin-orders/useFilteredAdminOrders.types.ts
  code/src/containers/dashboard-tabs/messages/en.json
  code/src/containers/dashboard-tabs/messages/uk.json
  code/src/context/drawer/DrawerContext.tsx
  code/src/hooks/use-filters-with-apply/deserialize-from-query-string/deserializeFromQueryString.ts
  code/src/hooks/use-filters-with-apply/parse-filters-from-params/parseFiltersFromParams.ts
  code/src/hooks/use-filters-with-apply/parse-serialized-range/parseSerializedRange.ts
  code/src/hooks/use-filters-with-apply/parse-serialized-set/parseSerializedSet.ts
  code/src/hooks/use-filters-with-apply/serialize-to-query-string/serializeToQueryString.ts
  code/src/hooks/use-filters-with-apply/useFiltersWithApply.ts
  code/src/hooks/use-filters-with-apply/useFiltersWithApply.types.ts
  code/src/store/api/ordersApi.ts
  code/src/types/common.ts
  code/src/types/order.types.ts
  code/src/utils/create-url-path/createUrlPath.test.tsx
  code/src/utils/create-url-path/createUrlPath.ts
  code/src/utils/time-span-to-date-range/timeSpanToDateRange.ts
  mock-backend/src/controllers/orderConroller.js
  mock-backend/src/data/mokedOrders.js
  mock-backend/src/utils/filterUtils.js
Labels: feature, frontend, ui, dashboard, sprint 4

#349 Added products table
  code/src/constants/common-messages/en.json
  code/src/constants/common-messages/uk.json
  code/src/containers/dashboard-tabs/components/products-tab/ProductsTab.test.tsx
  code/src/containers/dashboard-tabs/components/products-tab/ProductsTab.tsx
  code/src/containers/dashboard-tabs/messages/en.json
  code/src/containers/dashboard-tabs/messages/uk.json
  code/src/containers/tables/orders-table/OrdersTable.test.tsx
  code/src/containers/tables/products-table/ProductsTable.constants.ts
  code/src/containers/tables/products-table/ProductsTable.scss
  code/src/containers/tables/products-table/ProductsTable.test.tsx
  code/src/containers/tables/products-table/ProductsTable.tsx
  code/src/containers/tables/products-table/ProductsTable.types.ts
  code/src/containers/tables/products-table/components/products-table-body/ProductsTableBody.scss
  code/src/containers/tables/products-table/components/products-table-body/ProductsTableBody.test.tsx
  code/src/containers/tables/products-table/components/products-table-body/ProductsTableBody.tsx
  code/src/containers/tables/products-table/components/products-table-head/ProductsTableHead.scss
  code/src/containers/tables/products-table/components/products-table-head/ProductsTableHead.test.tsx
  code/src/containers/tables/products-table/components/products-table-head/ProductsTableHead.tsx
  code/src/containers/tables/products-table/messages/en.json
  code/src/containers/tables/products-table/messages/index.ts
  code/src/containers/tables/products-table/messages/uk.json
  code/src/messages.ts
  code/src/types/product.types.ts
  code/src/utils/get-category-from-tags/getCategoryFromTags.test.ts
  code/src/utils/get-category-from-tags/getCategoryFromTags.ts
Labels: feature, frontend, sprint 4

#352 Created variants for app-input
  code/src/components/app-input/AppInput.scss
  code/src/components/app-input/AppInput.tsx
  code/src/components/app-input/AppInput.types.ts
Labels: feature, frontend, sprint 4

#351 Fix header sign-in bug
  code/src/components/app-select/AppSelect.tsx
  code/src/containers/dashboard-tabs/components/orders-tab-filter-drawer/OrdersTabFilterDrawer.tsx
Labels: bug, frontend, sprint 4

#353 Implemented change product quantity logic with backend requests
  code/src/constants/common-messages/en.json
  code/src/constants/common-messages/uk.json
  code/src/constants/methods.ts
  code/src/constants/requests.ts
  code/src/containers/cart-drawer/CartDrawer.test.tsx
  code/src/containers/cart-drawer/CartDrawer.tsx
  code/src/hooks/use-update-cart-item-quantity/useUpdateCartItemQuantity.test.ts
  code/src/hooks/use-update-cart-item-quantity/useUpdateCartItemQuantity.ts
  code/src/hooks/use-user-cart-items/useUserCartItems.test.ts
  code/src/hooks/use-user-cart-items/useUserCartItems.ts
  code/src/pages/cart/CartPage.test.tsx
  code/src/pages/cart/CartPage.tsx
  code/src/pages/cart/components/cart-item/CartItem.scss
  code/src/pages/cart/components/cart-item/CartItem.test.tsx
  code/src/pages/cart/components/cart-item/CartItem.tsx
  code/src/store/api/cartApi.ts
  code/src/types/cart.types.ts
  mock-backend/src/controllers/cartController.js
  mock-backend/src/routes/cartRoutes.js
Labels: feature, frontend, sprint 4

#354 Tests for useFiltersWithApply and related utils
  code/src/hooks/use-filters-with-apply/check-supported-serialized-filter/checkSupportedSerializedFilter.test.ts
  code/src/hooks/use-filters-with-apply/check-supported-serialized-filter/checkSupportedSerializedFilter.ts
  code/src/hooks/use-filters-with-apply/deserialize-from-query-string/deserializeFromQueryString.test.ts
  code/src/hooks/use-filters-with-apply/deserialize-from-query-string/deserializeFromQueryString.ts
  code/src/hooks/use-filters-with-apply/parse-filters-from-params/parseFiltersFromParams.test.ts
  code/src/hooks/use-filters-with-apply/parse-filters-from-params/parseFiltersFromParams.ts
  code/src/hooks/use-filters-with-apply/parse-serialized-range/parseSerializedRange.test.ts
  code/src/hooks/use-filters-with-apply/parse-serialized-range/parseSerializedRange.ts
  code/src/hooks/use-filters-with-apply/parse-serialized-set/parseSerializedSet.test.ts
  code/src/hooks/use-filters-with-apply/parse-serialized-set/parseSerializedSet.ts
  code/src/hooks/use-filters-with-apply/serialize-to-query-string/serializeToQueryString.test.ts
  code/src/hooks/use-filters-with-apply/useFiltersWithApply.test.ts
  code/src/utils/time-span-to-date-range/timeSpanToDateRange.test.ts
Labels: feature, frontend, tests, sprint 4

#358 Created util function for filtering products by category
  code/src/constants/routes.ts
  code/src/layouts/header/components/header-categories/HeaderCategories.tsx
  code/src/pages/products/ProductsPage.test.tsx
  code/src/pages/products/ProductsPage.tsx
  code/src/pages/products/messages/en.json
  code/src/pages/products/messages/uk.json
  code/src/utils/filter-products-by-category/categoryFilter.test.ts
  code/src/utils/filter-products-by-category/categoryFilter.ts
Labels: feature, frontend, ui, sprint 4

#376 Fix cypress translation issue
  code/src/pages/products/ProductsPage.test.tsx
  code/src/pages/products/ProductsPage.tsx
  e2e/cypress/test_module/cypress/support/commands.ts
  e2e/cypress/test_module/cypress/support/index.ts
  e2e/cypress/test_module/cypress/support/step_definitions/auth.steps.ts
  e2e/cypress/test_module/cypress/support/step_definitions/home-page-general.steps.ts
  e2e/cypress/test_module/cypress/support/step_definitions/products-page.steps.ts
Labels: bug, frontend, tests

#360 Add tests for filter-related functionality (UI related part)
  code/config/setup-tests.js
  code/src/containers/dashboard-orders-filter-drawer/DashboardOrdersFilterDrawer.test.tsx
  code/src/containers/dashboard-orders-filter-drawer/DashboardOrdersFilterDrawer.tsx
  code/src/containers/dashboard-orders-filter-drawer/components/filter-record-accordion/FilterRecordAccordion.test.tsx
  code/src/containers/dashboard-orders-filter-drawer/components/filter-record-accordion/FilterRecordAccordion.tsx
  code/src/containers/dashboard-orders-filter-drawer/hooks/use-filtered-admin-orders/useFilteredAdminOrders.test.ts
  code/src/containers/forms/delivery-form/DeliveryForm.test.tsx
  code/src/pages/dashboard/dashboard-orders/DashboardOrdersPage.test.tsx
  code/src/pages/dashboard/dashboard-orders/DashboardOrdersPage.tsx
Labels: frontend, tests, dashboard, sprint 4

#367 Created e2e tests for the cart page
  code/src/containers/cart-drawer/CartDrawer.tsx
  code/src/layouts/header/components/header-toolbar/HeaderToolbar.tsx
  code/src/pages/cart/CartPage.tsx
  code/src/pages/cart/components/cart-item/CartItem.tsx
  code/src/pages/cart/components/empty-cart/EmptyCart.tsx
  e2e/cypress/test_module/cypress/features/cart-page/cart-page.feature
  e2e/cypress/test_module/cypress/fixtures/global-data.ts
  e2e/cypress/test_module/cypress/fixtures/routes.ts
  e2e/cypress/test_module/cypress/support/page_objects/home-pages.ts
  e2e/cypress/test_module/cypress/support/step_definitions/cart-page.steps.ts
  e2e/cypress/test_module/cypress/support/step_definitions/common.steps.ts
  e2e/cypress/test_module/cypress/support/step_definitions/home-page-general.steps.ts
  e2e/cypress/test_module/package-lock.json
  e2e/cypress/test_module/package.json
Labels: frontend, tests, sprint 4

#375 Fixed the request issue to backend. Changed the infinite value to 1000
  code/src/pages/products/ProductsPage.test.tsx
  code/src/pages/products/ProductsPage.tsx
Labels: bug, frontend, ui, sprint 4

#369 Add sorting to orders on admin panel
  code/src/components/app-table/components/app-table-sort-label/AppTableSortLabel.test.tsx
  code/src/components/app-table/components/app-table-sort-label/AppTableSortLabel.tsx
  code/src/components/app-table/components/app-table-sort-label/AppTableSortLabel.types.ts
  code/src/constants/deliveryMethods.ts
  code/src/containers/dashboard-orders-filter-drawer/DashboardOrdersFilterDrawer.test.tsx
  code/src/containers/dashboard-orders-filter-drawer/DashboardOrdersFilterDrawer.tsx
  code/src/containers/dashboard-orders-filter-drawer/hooks/use-filtered-admin-orders/useFilteredAdminOrders.test.ts
  code/src/containers/dashboard-orders-filter-drawer/hooks/use-filtered-admin-orders/useFilteredAdminOrders.ts
  code/src/containers/forms/delivery-form/DeliveryForm.tsx
  code/src/containers/tables/orders-table/OrdersTable.test.tsx
  code/src/containers/tables/orders-table/OrdersTable.tsx
  code/src/containers/tables/orders-table/components/orders-table-body/OrdersTableBody.test.tsx
  code/src/containers/tables/orders-table/components/orders-table-body/OrdersTableBody.tsx
  code/src/containers/tables/orders-table/components/orders-table-head/OrdersTableHead.constants.ts
  code/src/containers/tables/orders-table/components/orders-table-head/OrdersTableHead.scss
  code/src/containers/tables/orders-table/components/orders-table-head/OrdersTableHead.test.tsx
  code/src/containers/tables/orders-table/components/orders-table-head/OrdersTableHead.tsx
  code/src/hooks/use-filters-with-apply/useFiltersWithApply.types.ts
  code/src/pages/dashboard/dashboard-orders/DashboardOrdersPage.tsx
  code/src/store/api/ordersApi.ts
  code/src/types/common.ts
  code/src/types/order.types.ts
  mock-backend/src/controllers/orderConroller.js
  mock-backend/src/controllers/productController.js
  mock-backend/src/data/mokedOrders.js
  mock-backend/src/services/authService.js
  mock-backend/src/utils/sortUtils.js
Labels: feature, dashboard

#363 Add lang param to fetch items by different language
  code/src/constants/requests.ts
  code/src/containers/best-sellers/BestSellers.test.tsx
  code/src/containers/best-sellers/BestSellers.tsx
  code/src/containers/dashboard-orders-filter-drawer/hooks/use-filtered-admin-orders/useFilteredAdminOrders.test.ts
  code/src/containers/dashboard-orders-filter-drawer/hooks/use-filtered-admin-orders/useFilteredAdminOrders.ts
  code/src/hooks/use-get-cart/useGetCart.test.ts
  code/src/hooks/use-get-cart/useGetCart.ts
  code/src/pages/orders/OrdersPage.tsx
  code/src/pages/products/ProductsPage.test.tsx
  code/src/pages/products/ProductsPage.tsx
  code/src/store/api/cartApi.ts
  code/src/store/api/ordersApi.ts
  code/src/types/cart.types.ts
  code/src/types/common.ts
  code/src/types/order.types.ts
  code/src/types/product.types.ts
Labels: feature, frontend, sprint 4

#378 Changed header component to switch category label language
  code/src/layouts/header/components/header-categories/HeaderCategories.constants.ts
  code/src/layouts/header/components/header-categories/HeaderCategories.tsx
Labels: bug, frontend, ui, sprint 4

#371 Added new product form
  code/src/components/app-checkbox/AppCheckbox.tsx
  code/src/components/app-checkbox/AppCheckbox.types.ts
  code/src/components/app-form-helper-text/AppFormHelperText.tsx
  code/src/components/app-select/AppSelect.tsx
  code/src/constants/api-tags.ts
  code/src/constants/locales.ts
  code/src/constants/requests.ts
  code/src/containers/forms/new-product-form/NewProductForm.constants.ts
  code/src/containers/forms/new-product-form/NewProductForm.scss
  code/src/containers/forms/new-product-form/NewProductForm.tsx
  code/src/containers/forms/new-product-form/NewProductForm.types.ts
  code/src/containers/forms/new-product-form/components/image-preview/ImagePreview.tsx
  code/src/containers/forms/new-product-form/messages/en.json
  code/src/containers/forms/new-product-form/messages/index.ts
  code/src/containers/forms/new-product-form/messages/uk.json
  code/src/messages.ts
  code/src/pages/dashboard/dashboard-new-product/DashboardNewProductPage.scss
  code/src/pages/dashboard/dashboard-new-product/DashboardNewProductPage.tsx
  code/src/pages/dashboard/dashboard-new-product/messages/en.json
  code/src/pages/dashboard/dashboard-new-product/messages/uk.json
  code/src/store/api/productsApi.ts
  code/src/types/product.types.ts
  code/src/utils/validators/productCreationScheme.ts
  mock-backend/src/controllers/productController.js
  mock-backend/src/routes/productRoutes.js
Labels: feature, frontend, sprint 4

#381 Improved coverage of new product form
  code/src/containers/forms/new-product-form/NewProductForm.constants.ts
  code/src/containers/forms/new-product-form/NewProductForm.test.tsx
  code/src/containers/forms/new-product-form/NewProductForm.tsx
  code/src/containers/forms/new-product-form/NewProductForm.types.ts
  code/src/containers/forms/new-product-form/components/image-preview/ImagePreview.test.tsx
  code/src/containers/forms/new-product-form/components/image-preview/ImagePreview.tsx
  code/src/containers/forms/new-product-form/messages/uk.json
  code/src/pages/dashboard/dashboard-new-product/DashboardNewProductPage.test.tsx
  code/src/utils/validators/productCreationScheme.ts
Labels: frontend, tests, sprint 4

#403 Add useErrorPageRedirect hook
  code/src/constants/routes.ts
  code/src/hooks/use-error-page-redirect/useErrorPageRedirect.constants.ts
  code/src/hooks/use-error-page-redirect/useErrorPageRedirect.test.tsx
  code/src/hooks/use-error-page-redirect/useErrorPageRedirect.tsx
  code/src/hooks/use-error-page-redirect/useErrorPageRedirect.types.ts
  code/src/pages/not-found/NotFoundPage.test.tsx
  code/src/pages/not-found/NotFoundPage.tsx
Labels: feature, frontend, spint 5

#404 Exclude some files from stryker testing
  code/config/jest.config.js
  code/stryker.conf.js
Labels: frontend, tests, spint 5

#406 Remove automatic fetch of cart for admin and manager
  code/src/hooks/use-get-cart/useGetCart.test.ts
  code/src/hooks/use-get-cart/useGetCart.ts
Labels: bug, priority:low, frontend, spint 5

#402 Dashboard order details page
  code/src/constants/common-messages/en.json
  code/src/constants/common-messages/uk.json
  code/src/constants/common.ts
  code/src/constants/requests.ts
  code/src/constants/routes.ts
  code/src/containers/order-item/OrderItem.test.tsx
  code/src/containers/order-item/OrderItem.tsx
  code/src/containers/tables/orders-table/OrdersTable.constants.ts
  code/src/containers/tables/orders-table/OrdersTable.test.tsx
  code/src/containers/tables/orders-table/components/orders-table-body/OrdersTableBody.test.tsx
  code/src/containers/tables/orders-table/components/orders-table-body/OrdersTableBody.tsx
  code/src/containers/tables/orders-table/messages/en.json
  code/src/containers/tables/orders-table/messages/uk.json
  code/src/messages.ts
  code/src/pages/dashboard-order-details/DashboardOrderDetails.constants.ts
  code/src/pages/dashboard-order-details/DashboardOrderDetailsPage.scss
  code/src/pages/dashboard-order-details/DashboardOrderDetailsPage.test.tsx
  code/src/pages/dashboard-order-details/DashboardOrderDetailsPage.tsx
  code/src/pages/dashboard-order-details/messages/en.json
  code/src/pages/dashboard-order-details/messages/index.ts
  code/src/pages/dashboard-order-details/messages/uk.json
  code/src/routes/protectedRoutes.tsx
  code/src/store/api/ordersApi.ts
  code/src/types/order.types.ts
  mock-backend/src/controllers/orderConroller.js
  mock-backend/src/routes/orderRoutes.js
Labels: feature, frontend, spint 5

#405 Restricted visible tabs for admin and manager
  code/src/layouts/dashboard-layout/DashboardLayout.constants.tsx
  code/src/layouts/dashboard-layout/DashboardLayout.test.tsx
  code/src/layouts/dashboard-layout/DashboardLayout.tsx
  code/src/layouts/dashboard-layout/DashboardLayout.types.ts
  code/src/layouts/dashboard-layout/components/dashboard-admin-tab-layout/DashboardAdminLayout.constants.tsx
  code/src/layouts/dashboard-layout/components/dashboard-admin-tab-layout/DashboardAdminLayout.test.tsx
  code/src/layouts/dashboard-layout/components/dashboard-admin-tab-layout/DashboardAdminLayout.tsx
  code/src/layouts/dashboard-layout/components/dashboard-manager-tab-layout/DashboardManagerLayout.constants.tsx
  code/src/layouts/dashboard-layout/components/dashboard-manager-tab-layout/DashboardManagerLayout.test.tsx
  code/src/layouts/dashboard-layout/components/dashboard-manager-tab-layout/DashboardManagerLayout.tsx
  code/src/layouts/dashboard-layout/components/dashboard-tab-layout/DashboardTabLayout.scss
  code/src/layouts/dashboard-layout/components/dashboard-tab-layout/DashboardTabLayout.test.tsx
  code/src/layouts/dashboard-layout/components/dashboard-tab-layout/DashboardTabLayout.tsx
  code/src/layouts/dashboard-layout/components/dashboard-tab/DashboardTab.test.tsx
  code/src/layouts/dashboard-layout/components/dashboard-tab/DashboardTab.tsx
  code/src/layouts/dashboard-layout/utils/getDashboardLayoutByRole.test.tsx
  code/src/layouts/dashboard-layout/utils/getDashboardLayoutByRole.tsx
  code/src/layouts/header/components/header-toolbar/HeaderToolbar.tsx
  code/src/pages/dashboard/DashboardPage.tsx
  code/src/routes/protectedRoutes.tsx
Labels: feature, frontend, refactor, dashboard, spint 5

#412 Fixed banner height when language changes
  code/src/containers/intro-banner/IntroBanner.scss
  code/src/containers/intro-banner/messages/en.json
  code/src/containers/intro-banner/messages/uk.json
Labels: bug, frontend, spint 5

#411 Fix sorting arrows on manager orders tab
  code/src/containers/dashboard-orders-filter-drawer/hooks/use-filtered-admin-orders/useFilteredAdminOrders.test.ts
  code/src/containers/dashboard-orders-filter-drawer/hooks/use-filtered-admin-orders/useFilteredAdminOrders.ts
  code/src/containers/tables/orders-table/components/orders-table-head/OrdersTableHead.scss
  code/src/containers/tables/orders-table/components/orders-table-head/OrdersTableHead.test.tsx
  code/src/containers/tables/orders-table/components/orders-table-head/OrdersTableHead.tsx
Labels: bug, frontend

#416 Fix subintro with Ukraine translation
  code/src/containers/subintro/Subintro.scss
  code/src/containers/subintro/components/SubintroItem.tsx
  code/src/containers/subintro/messages/uk.json
Labels: bug

#407 Increased coverage of HeaderToolbar and refactored it
  code/src/components/app-link/AppLink.tsx
  code/src/hooks/use-logout/useLogout.test.ts
  code/src/hooks/use-logout/useLogout.ts
  code/src/layouts/header/components/header-buttons/header-cart-button/HeaderCartButton.test.tsx
  code/src/layouts/header/components/header-buttons/header-cart-button/HeaderCartButton.tsx
  code/src/layouts/header/components/header-buttons/header-dashboard-button/HeaderDashboardButton.test.tsx
  code/src/layouts/header/components/header-buttons/header-dashboard-button/HeaderDashboardButton.tsx
  code/src/layouts/header/components/header-buttons/header-login-button/HeaderLoginButton.test.tsx
  code/src/layouts/header/components/header-buttons/header-login-button/HeaderLoginButton.tsx
  code/src/layouts/header/components/header-buttons/header-logout-button/HeaderLogoutButton.test.tsx
  code/src/layouts/header/components/header-buttons/header-logout-button/HeaderLogoutButton.tsx
  code/src/layouts/header/components/header-buttons/header-orders-button/HeaderOrdersButton.test.tsx
  code/src/layouts/header/components/header-buttons/header-orders-button/HeaderOrdersButton.tsx
  code/src/layouts/header/components/header-categories/HeaderCategories.test.tsx
  code/src/layouts/header/components/header-search-input/HeaderSearchInput.test.tsx
  code/src/layouts/header/components/header-search-input/HeaderSearchInput.tsx
  code/src/layouts/header/components/header-toolbar/HeaderToolbar.test.tsx
  code/src/layouts/header/components/header-toolbar/HeaderToolbar.tsx
  code/src/layouts/header/components/header-toolbar/header-admin-toolbar/HeaderAdminToolbar.test.tsx
  code/src/layouts/header/components/header-toolbar/header-admin-toolbar/HeaderAdminToolbar.tsx
  code/src/layouts/header/components/header-toolbar/header-shop-manager-toolbar/HeaderShopManagerToolbar.test.tsx
  code/src/layouts/header/components/header-toolbar/header-shop-manager-toolbar/HeaderShopManagerToolbar.tsx
  code/src/layouts/header/components/header-toolbar/header-unauthorized-user-toolbar/HeaderUnauthorizedUserToolbar.test.tsx
  code/src/layouts/header/components/header-toolbar/header-unauthorized-user-toolbar/HeaderUnauthorizedUserToolbar.tsx
  code/src/layouts/header/components/header-toolbar/header-user-toolbar/HeaderUserToolbar.test.tsx
  code/src/layouts/header/components/header-toolbar/header-user-toolbar/HeaderUserToolbar.tsx
  code/src/layouts/header/utils/get-header-toolbar-by-role/getHeaderToolbarByRole.test.tsx
  code/src/layouts/header/utils/get-header-toolbar-by-role/getHeaderToolbarByRole.tsx
  code/src/utils/calculate-cart-items-counter/calculateCartItemsCounter.test.ts
  code/src/utils/calculate-cart-items-counter/calculateCartItemsCounter.ts
  e2e/cypress/test_module/cypress/support/step_definitions/logout.steps.ts
Labels: frontend, refactor, tests, spint 5

#417 Create product details page
  code/src/components/product-card/ProductCard.test.tsx
  code/src/components/product-card/ProductCard.tsx
  code/src/constants/requests.ts
  code/src/constants/routes.ts
  code/src/messages.ts
  code/src/pages/product-details/ProductDetails.types.ts
  code/src/pages/product-details/ProductDetailsPage.scss
  code/src/pages/product-details/ProductDetailsPage.tsx
  code/src/pages/product-details/ProductsDetailsPage.constants.tsx
  code/src/pages/product-details/ProductsDetailsPage.test.tsx
  code/src/pages/product-details/components/product-details-container/ProductDetailsContainer.scss
  code/src/pages/product-details/components/product-details-container/ProductDetailsContainer.test.tsx
  code/src/pages/product-details/components/product-details-container/ProductDetailsContainer.tsx
  code/src/pages/product-details/messages/en.json
  code/src/pages/product-details/messages/index.ts
  code/src/pages/product-details/messages/uk.json
  code/src/routes/guestRoutes.tsx
  code/src/store/api/productsApi.ts
  code/src/styles/global.scss
  code/src/types/product.types.ts
  mock-backend/src/controllers/productController.js
  mock-backend/src/routes/productRoutes.js
Labels: feature, frontend, ui, spint 5

#421 added e2e for dashboard page
  code/src/components/app-range-slider/AppRangeSlider.tsx
  code/src/containers/dashboard-orders-filter-drawer/DashboardOrdersFilterDrawer.tsx
  code/src/containers/forms/new-product-form/NewProductForm.constants.ts
  code/src/containers/forms/new-product-form/NewProductForm.tsx
  code/src/containers/forms/new-product-form/components/image-preview/ImagePreview.tsx
  code/src/containers/tables/orders-table/components/orders-table-head/OrdersTableHead.tsx
  code/src/layouts/dashboard-layout/components/dashboard-tab/DashboardTab.tsx
  code/src/pages/dashboard/dashboard-new-product/DashboardNewProductPage.tsx
  code/src/pages/dashboard/dashboard-orders/DashboardOrdersPage.tsx
  code/src/pages/dashboard/dashboard-products/DashboardProductsPage.tsx
  e2e/cypress/test_module/cypress/features/dashboard-page/dashboard-page.feature
  e2e/cypress/test_module/cypress/features/dashboard-page/new-product/new-product.feature
  e2e/cypress/test_module/cypress/features/dashboard-page/orders-filters/orders-filters.feature
  e2e/cypress/test_module/cypress/features/home-page/home-page-manager.feature
  e2e/cypress/test_module/cypress/fixtures/constants.ts
  e2e/cypress/test_module/cypress/support/step_definitions/dashboard.steps.ts
  e2e/cypress/test_module/cypress/support/step_definitions/home-page-manager.steps.ts
  e2e/cypress/test_module/cypress/support/step_definitions/new-product.steps.ts
  e2e/cypress/test_module/cypress/support/step_definitions/orders-filters.steps.ts
Labels: frontend, tests, dashboard, spint 5

#422 Added update product route
  code/src/constants/regexes.ts
  code/src/constants/requests.ts
  code/src/constants/routes.ts
  code/src/layouts/dashboard-layout/components/dashboard-tab-container/DashboardTabContainer.tsx
  code/src/messages.ts
  code/src/pages/dashboard-order-details/DashboardOrderDetails.constants.ts
  code/src/pages/dashboard-order-details/messages/en.json
  code/src/pages/dashboard-order-details/messages/uk.json
  code/src/pages/dashboard/dashboard-update-product/DashboardUpdateProductPage.constants.ts
  code/src/pages/dashboard/dashboard-update-product/DashboardUpdateProductPage.scss
  code/src/pages/dashboard/dashboard-update-product/DashboardUpdateProductPage.test.tsx
  code/src/pages/dashboard/dashboard-update-product/DashboardUpdateProductPage.tsx
  code/src/pages/dashboard/dashboard-update-product/DashboardUpdateProductPage.types.ts
  code/src/pages/dashboard/dashboard-update-product/components/dashboard-update-product-container/DashboardUpdateProductContainer.test.tsx
  code/src/pages/dashboard/dashboard-update-product/components/dashboard-update-product-container/DashboardUpdateProductContainer.tsx
  code/src/pages/dashboard/dashboard-update-product/messages/en.json
  code/src/pages/dashboard/dashboard-update-product/messages/index.ts
  code/src/pages/dashboard/dashboard-update-product/messages/uk.json
  code/src/routes/protectedRoutes.tsx
  code/src/store/api/productsApi.ts
  code/src/types/product.types.ts
  code/src/utils/is-uuid-valid/isUUIDValid.test.ts
  code/src/utils/is-uuid-valid/isUUIDValid.ts
  mock-backend/src/controllers/productController.js
  mock-backend/src/data/managerProducts.js
  mock-backend/src/routes/productRoutes.js
Labels: feature, frontend, spint 5

#425 Changed footer banner translation
  code/src/layouts/footer/messages/uk.json
Labels: feature, frontend, spint 5

#424 Changed hover property for footer
  code/src/layouts/footer/Footer.tsx
Labels: bug, frontend, ui

#423 Added redirect to products details
  code/src/containers/order-item/OrderItem.test.tsx
  code/src/containers/order-item/components/order-item-details/OrderItemDetails.tsx
  code/src/containers/order-item/components/order-item-details/OrderProductDetails.test.tsx
  code/src/containers/order-item/components/order-product-item/OrderProductItem.scss
  code/src/containers/order-item/components/order-product-item/OrderProductItem.test.tsx
  code/src/containers/order-item/components/order-product-item/OrderProductItem.tsx
  code/src/containers/orders-list/OrdersList.test.tsx
  mock-backend/src/data/mokedOrders.js
Labels: feature, frontend, spint 5

#429 Changed global font-family
  code/src/containers/order-item/OrderItem.scss
  code/src/containers/tables/orders-table/components/orders-table-body/OrdersTableBody.scss
  code/src/styles/base/_root.scss
  code/src/styles/foundation/_typography.scss
  code/src/styles/foundation/_variables.scss
Labels: bug, frontend, spint 5
